### PR TITLE
bio.tools story

### PR DESCRIPTION
**Pull request by albangaignard**
A simple page to share "success stories". Thanks @nsjuty for the revisions of the text. 

The updated menu: 
Capture d’écran 2023-05-22 à 16 10 15

The whole page, one section per story
Capture d’écran 2023-05-22 à 16 09 51

### CODE REVIEW

**Review by ljgarcia — COMMENTED** [review]
I would call it "User stories" or "Success stories" only "stories" does not say enough.
@nsjuty @CaroleGoble please advise, thanks

**Review by ivanmicetic — COMMENTED** [review]
Looks good. I also like "Bioschemas in action" as section title.

I would hide the URL to the ttl file (change to hyperlink) as well as expand or explain the link under "Further reading".

**Review by ivanmicetic — APPROVED** [review]
Looks good

**Comment by albangaignard** [comment]
Thanks @nsjuty, I fixed it.

**Pull request merged**
