### PR TITLE
Auto-Rendering Profile

### PR DESCRIPTION
**Pull request by sahar-frikha**
This pull request has been created by a guithub action, after adding/updating a profile in the specifications repo.

### CODE REVIEW

**Review by ljgarcia — CHANGES_REQUESTED** [review]
The profile created from GitHub actions looks fine (after updating hierarchy and redirections which do not work well in GitHub actions). However, some information is missing and should be added to this PR.
@sneumann @gtsueng @ivanmicetic could you please add the use cases? They should go to /useCases/DefinedTerm and also the group this profile should go to? I would suggest Dataset. 
There are no embedded examples in the page, cannot those be created with DDE as well? If not, see if you can add a couple by hand. Not mandatory/blocking but nice to have.
image

Thanks.

**Comment by ljgarcia** [comment]
@sneumann @gtsueng @ivanmicetic  any updates? Thanks

**Comment by sneumann** [comment]
As I can't edit this PR, I have created #808 to replace this one. 
I hope to have adressed the requested changes. 
Yours, Steffen

**Comment by ljgarcia** [comment]
> As I can't edit this PR, I have created #808 to replace this one. I hope to have adressed the requested changes. Yours, Steffen

When trying your repo, I get an error for the DefineTerm.html "mapping values are not allowed in this context at line 56 column 12". I will implement your changes here. Someone else will have to do the review

**Review by ljgarcia — APPROVED** [review]
It can go now

**Comment by sneumann** [comment]
Hi, I am still unable to test my changes locally, so thanks for catching `mapping values are not allowed...`.

**Pull request merged**
