### PR TITLE
Fixing group issues

### PR DESCRIPTION
**Pull request by bedroesb**
These changes will fix the problems described here: https://github.com/BioSchemas/specifications/issues/626

### CODE REVIEW

**Comment by bedroesb** [comment]
@ljgarcia I think this comment is not related to this PR? The fact that the url was not working had not to do with a redirect missing, but was a typo (quote was not closed)  that is already present for a very long time

**Comment by bedroesb** [comment]
This PR is fixing problems that are there in the current deployment and does not hold back redirect changes

**Comment by ljgarcia** [comment]
The comment is related to this PR. I understand the redirection problem does not come from this PR but I do not see the point in processing the PR right now knowing that the link to draft/release are wrong.

**Comment by bedroesb** [comment]
I understand. But these wrong links towards release and draft are currently there already ... This is indeed a temporary solution if things will change, but one better than what now is in place. I don't see the reason of keeping broken urls online vs fixing them.

If the redirects change, we have to go through all urls in the website anyway. Just my opinion

**Review by ljgarcia — APPROVED** [review]

**Pull request merged**
