### PR TITLE
Publish ComputationalTools 0.5-DRAFT

### PR DESCRIPTION
**Pull request by AlasdairGray**
Relates to issue [#454](https://github.com/BioSchemas/specifications/issues/454)

### CODE REVIEW

**Review by ljgarcia — CHANGES_REQUESTED** [review]
Action required for this PR:
* Tools group profiles should be updated (updating leaders for later).

Future profile update:
* Profile according to DRAFT 0.5 but still ToDos there and properties outside the scope of schema.org, all that need to be addressed in DRAFT 0.6

**Comment by alaninmcr** [comment]
I have great doubts about the ComputationTool / Tool specification. It says that it hasInput and serviceOutput of type MediaObject. This is (in my opinion) very wrong. A MediaObject would be something that satisfies a Tool's input (or output) when the Tool is / has been run. It is **not** a placeholder to be filled in.

**Comment by AlasdairGray** [comment]
> I have great doubts about the ComputationTool / Tool specification. It says that it hasInput and serviceOutput of type MediaObject. This is (in my opinion) very wrong. A MediaObject would be something that satisfies a Tool's input (or output) when the Tool is / has been run. It is **not** a placeholder to be filled in.

I have raised this as an issue [465](https://github.com/BioSchemas/specifications/issues/465) for the next draft release. It should not prevent the 0.5-DRAFT from being pushed to the website.

**Comment by AlasdairGray** [comment]
> Action required for this PR:
> 
> * Tools group profiles should be updated (updating leaders for later).

Can you clarify what you mean, and should this prevent the 0.5-DRAFT from making it to the website?

**Comment by ljgarcia** [comment]
> > Action required for this PR:
> > 
> > * Tools group profiles should be updated (updating leaders for later).
> 
> Can you clarify what you mean, and should this prevent the 0.5-DRAFT from making it to the website?

It is a broken link as the profile was renamed ComputationalTool. It was before Tool. It does not prevent publishing the ComputationalTool DRAFT 0.5 but I think updating those links is part of the PR.

Go to https://bioschemas.org/groups/Tools/, the list of profiles should go now to ComputationalTool. Thank link on the PR is broken.

**Comment by AlasdairGray** [comment]
> Future profile update:
> 
> * Profile according to DRAFT 0.5 but still ToDos there and properties outside the scope of schema.org, all that need to be addressed in DRAFT 0.6

These have been logged as issues [#466](https://github.com/BioSchemas/specifications/issues/466) and [#467](https://github.com/BioSchemas/specifications/issues/467)

**Comment by AlasdairGray** [comment]
> > > Action required for this PR:
> > > 
> > > * Tools group profiles should be updated (updating leaders for later).
> > 
> > 
> > Can you clarify what you mean, and should this prevent the 0.5-DRAFT from making it to the website?
> 
> It is a broken link as the profile was renamed ComputationalTool. It was before Tool. It does not prevent publishing the ComputationalTool DRAFT 0.5 but I think updating those links is part of the PR.
> 
> Go to https://bioschemas.org/groups/Tools/, the list of profiles should go now to ComputationalTool. Thank link on the PR is broken.

Good spot. Fixed in a37d7de9159d2ba2b0401810187051660737d110

**Comment by AlasdairGray** [comment]
@ljgarcia are you happy with the resolution?

**Review by ljgarcia — APPROVED** [review]
Looks good

**Pull request merged**
