### PR TITLE
Added the RiskGONE deployment of ChemicalSubstance

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by AlasdairGray** [comment]
@egonw could you add a quick news item (bit like a tweet) like the other ones we have for deployments (see [here](https://bioschemas.org/news/tags.html#deployment)? They go in [this](https://github.com/BioSchemas/bioschemas.github.io/tree/master/pages/_news) directory.

**Comment by egonw** [comment]
> @egonw could you add a quick news item

@AlasdairGray, done: https://github.com/BioSchemas/bioschemas.github.io/commit/2319584cb1cc8ab37f6ddd1b30d2107f2b809e9d

**Review by AlasdairGray — APPROVED** [review]

**Comment by egonw** [comment]
> Example page https://h2020-riskgone.github.io/riskgone-materials/ does not seem to have ChemicalSubstance markup within it

Sorry about that. I fixed the link.

**Review by AlasdairGray — APPROVED** [review]

**Comment by AlasdairGray** [comment]
@egonw would it make sense to add other profiles such as Dataset and ScholarlyArticle to the site?

**Comment by egonw** [comment]
> @egonw would it make sense to add other profiles such as Dataset and ScholarlyArticle to the site?

yes, exactly what I want to do in the first Tox implementation study.

**Pull request merged**
