### PR TITLE
Feat/go web description

### PR DESCRIPTION
**Pull request by ricardoaat**
- Updated GoWeb description field and added image.
- Added GoCrawlit Tool to the list

### CODE REVIEW

**Comment by ricardoaat** [comment]
@rajido The changes are great! Thank you Rafa. I will merge the changes now.

**Comment by rajido** [comment]
I think you are right @ljgarcia. I have change as you suggested.

**Comment by ricardoaat** [comment]
@kcmcleod I have sorted the tools alphabetically. I will work in a better description for GoCrawlit tool and push it on another branch. I think this one is ready to merge now.

**Comment by kcmcleod** [comment]
go for it!

**Pull request merged**
