### PR TITLE
Remove spec property from profiles

### PR DESCRIPTION
**Pull request by kcmcleod**
removing *spec_mapping_url* property from all profiles & draft profiles
where necessary updating *cross_walk_url* and *use_cases_url*

### CODE REVIEW

**Comment by kcmcleod** [comment]
# devSpecs

Corrected :
* gene
* protein
* proteinAnnotation
* publicationIssue
* taxon

Issues:
* no idea what is happening with Course and CourseInstance; using very different naming
* There is no ProteinAnnotation 0.4-draft to link to
  * There is 0.5-draft and 0.6-draft and some unnumbered files. The latest edits were made by Serena Scollen to unnumbered files so no idea what is happening; [see folder](https://drive.google.com/drive/folders/0B0fE3oOZIq44c2dqVVRkaVZ6X2M)


# specs

Corrected:
* Event
* TrainingMaterial

Issues:
* Dataset is 0.3, but links to 0.3-DRAFT. Is the filename wrong?

**Comment by AlasdairGray** [comment]
> There is no ProteinAnnotation 0.4-draft to link to
> * There is 0.5-draft and 0.6-draft and some unnumbered files. The latest edits were made by Serena Scollen to unnumbered files so no idea what is happening; [see folder](https://drive.google.com/drive/folders/0B0fE3oOZIq44c2dqVVRkaVZ6X2M)

I've done some tidying up here. We now have the files for 0.3-DRAFT and 0.4-DRAFT but these both use old formats of the way we were developing profiles.

**Comment by AlasdairGray** [comment]
> * no idea what is happening with [Course](https://drive.google.com/drive/folders/1MSPkqrwgUX3QwsQY-aaAq8Wnl0swCrhv) and [CourseInstance](https://drive.google.com/drive/folders/1u1IufPtgyGgzKoaeopYCCcBvkFQ8cuZl); using very different naming

@njall can you fix the naming convention of your files so that they are 0.x-DRAFT

**Comment by AlasdairGray** [comment]
> Issues:
> 
> * [Dataset](https://drive.google.com/drive/folders/0B2tKthYRS0f5aEhkU1Q4aEE5TEU) is 0.3, but links to 0.3-DRAFT. Is the filename wrong?

That is simply we didn't update the metadata in the file and the filename when we made the release. We really need to formalise the workflow for releasing a profile.

**Comment by kcmcleod** [comment]
@AlasdairGray - Beacon is a mess, again Serena & Pascal are the culprits. 
* Pascal has 4 files called 'Beacon mapping up' that contain 'New properties for Biological Entity'. They seem to have nothing in common with Beacon and also seem identical. Should I delete or move to _old_files_ folder?
* Pascal has another 4 files called 'Beacon mapping simp' that could be a Beacon v0.1. They are a subset of the profile on the site. Again these files seem identical. 
* Pascal's 3rd set of 4 files are called 'Beacon mapping old'. They have the same profile has the 'Beacon mapping simp' but are in a different version of the gSheet.
* Pascal's 4th set of 4 files are called 'Beacon mapping' and have the same profiles as 'Beacon mapping simp' & 'Beacon mapping old' the rest.

Should I take the version with the latest gSheet and rename it as beacon v0.1? What should I do with the rest? If I can't delete them, do I have to keep all 4 copies?

Serena has 2 identical files called 'Beacon mapping 0.2' that are using the latest version of the sheet. There is also a doc from Ricardo that uses the same version of the sheet and has the same profile, but is called 0.2-draft. All 3 of these files have the same profile content as the bioschemas site (which is 0.2-draft).  I only need 1 of these files, what do I do with the other 2? Delete or move to _old_files_?

**Comment by kcmcleod** [comment]
> > There is no ProteinAnnotation 0.4-draft to link to
> > 
> > * There is 0.5-draft and 0.6-draft and some unnumbered files. The latest edits were made by Serena Scollen to unnumbered files so no idea what is happening; [see folder](https://drive.google.com/drive/folders/0B0fE3oOZIq44c2dqVVRkaVZ6X2M)
> 
> I've done some tidying up here. We now have the files for 0.3-DRAFT and 0.4-DRAFT but these both use old formats of the way we were developing profiles.

@AlasdairGray - The ProteinAnnotation profile published on bioschemas.org is v0.4-DRAFT. However, it does not match the file you have named 0.4-DRAFT. Indeed the profile on the site does not match any of the profile sheets in the folder. 
Looking at Ricardo's yaml there is a link to a 'Protein Annotation' file in the 'previous versions' folder. However, that does not match the contents on the site either. What do you want to?

**Comment by kcmcleod** [comment]
@AlasdairGray - ignoring the above issues with Beacon & ProteinAnnotation, Course, CourseInstance and TrainingMaterial, I believe the rest of the specs & drafts have the correct cross_walk_url links.

**Comment by kcmcleod** [comment]
@AlasdairGray - ProteinAnnotation and Beacon updated following our discussion

**Pull request merged**
