### PR TITLE
TOC style changes

### PR DESCRIPTION
**Pull request by bedroesb**
@AlasdairGray witht the title in place I forgot to adjust the padding. I also aligned the list marker with the content ones.

Before:
Screenshot from 2021-06-03 10-02-11

After:
Screenshot from 2021-06-03 10-13-14

We could off course differ the indentation of the list in the TOC copared to the content to let it stand out more...

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Happy with the TOC in either form.

@bedroesb the `<h3>` headings are still going under the nav bar for me on my machine. @ljgarcia are things behaving properly for you?

**Comment by bedroesb** [comment]
@AlasdairGray we could leave out H3 titles from the toc?

**Comment by AlasdairGray** [comment]
I would leave them in and just accept that there is a bug there. I don't think this is a major issue

**Comment by AlasdairGray** [comment]
@bedroesb is this PR waiting for approval or is there further development work planned?

**Comment by bedroesb** [comment]
@AlasdairGray for me it is the same, you can chose! If you like the current looks more you can close this PR.

**Review by AlasdairGray — APPROVED** [review]
This looks neater. Thanks @bedroesb

**Pull request merged**
