### PR TITLE
Add 08 release for Gene

### PR DESCRIPTION
**Pull request by ljgarcia**
In response to https://github.com/BioSchemas/specifications/issues/492
* add cardinality for associatedDisease and taxonomicRange following the one in Protein
* add suggestion on controlled vocabularies for taxonomicRange following the one in Protein

As the changes are minor, it goes straight to 0.8 RELEASE rather than a draft that will become release later

### CODE REVIEW

**Review by albangaignard — APPROVED** [review]
Works for me, tested on my local copy.

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
This needs to await the outcome of the community vote on what should be the version number. 

We will know this on Friday afternoon.

**Review by AlasdairGray — COMMENTED** [review]
Please update to 1.0-RELEASE

**Comment by ljgarcia** [comment]
@AlasdairGray @albangaignard update to 1.0-RELEASE done, please have a look, thanks.

**Review by AlasdairGray — APPROVED** [review]
Fixed link to previous version and corrected metadata in crosswalk file.

**Pull request merged**
