### PR TITLE
New MolecularEntity Profile for Chemicals group

### PR DESCRIPTION
**Pull request by ricardoaat**
- Added molecular entity profile
- Updated Chemicals group
- Added David, Anna and Egon to People

### CODE REVIEW

**Comment by ficolo** [comment]
+1

**Comment by nclopezo** [comment]
+1

**Comment by ricardoaat** [comment]
@AlasdairGray Added Molecular Type and link to the crosswalk and use cases

**Comment by ricardoaat** [comment]
Chemical and Chemical structure moved to MolecularEntity

**Pull request merged**
