### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ljgarcia**
Edited from the "Edit me" button.
We want "practice" the noun, not "practise" the verb, am I right?

### CODE REVIEW

**Comment by ljgarcia** [comment]
I created the pull request but it was Alasdair who created the pages (as far as I remember) so I would say I cannot be an assignee. I have removed myself.

**Comment by kcmcleod** [comment]
@ljgarcia - yes to best practice. Are you aware of the new tools page? http://bioschemas.org/tools/

**Comment by kcmcleod** [comment]
@leyla - /tools is deliberately hidden (not available from home page) because the content needs to be further improved.

**Comment by kcmcleod** [comment]
@ljgarcia - the tools page is not ready for publication, but is online because it was the only way we could get feedback (people were not willing to deal with PR). 

once finished, the current plan is to put it under 'about' in the menu and also link to it from the 'community' page.

**Comment by ljgarcia** [comment]
I understand now. @kcmcleod where would be the right place to provide feedback?

**Comment by kcmcleod** [comment]
@ljgarcia - Ricardo is using PRs for all changes. However, as it is hidden, others have directly edited the page. You can also create an issue in the specs repo with the 'website' tag; assign it to me or Ricardo

**Comment by AlasdairGray** [comment]
once finished, the current plan is to put it under 'about' in the menu and also link to it from the 'community' page.

I think that we need a separate menu item for tools, tutorials, and other training materials. Not sure what to call it so please suggest.
________________________________

Heriot-Watt University is The Times & The Sunday Times International University of the Year 2018

Founded in 1821, Heriot-Watt is a leader in ideas and solutions. With campuses and students across the entire globe we span the world, delivering innovation and educational excellence in business, engineering, design and the physical, social and life sciences.

This email is generated from the Heriot-Watt University Group, which includes:

  1.  Heriot-Watt University, a Scottish charity registered under number SC000278
  2.  Edinburgh Business School a Charity Registered in Scotland, SC026900. Edinburgh Business School is a company limited by guarantee, registered in Scotland with registered number SC173556 and registered office at Heriot-Watt University Finance Office, Riccarton, Currie, Midlothian, EH14 4AS
  3.  Heriot- Watt Services Limited (Oriam), Scotland's national performance centre for sport. Heriot-Watt Services Limited is a private limited company registered is Scotland with registered number SC271030 and registered office at Research & Enterprise Services Heriot-Watt University, Riccarton, Edinburgh, EH14 4AS.

The contents (including any attachments) are confidential. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system.

**Comment by ricardoaat** [comment]
I would suggest a new link for tools and another called "Docs" or "Documentation" and under this one having "Tutorials" and "Training Material"

- Home
- Join
- Meetings (or changing this to "Events")
- Specifications
  - Current
  - Draft
  - Live deploys
- Docs
  - Tutorials
  - Training material
- About
  - Community
  - People
  - Groups
  - Presentations

**Comment by AlasdairGray** [comment]
Are you suggesting that Tools be at the top level? It is missing from your suggestion.

Happy for Meetings to be relabelled Events.

I wonder if Join should be moved to the About sub menu.

**Comment by ricardoaat** [comment]
You are right, I have just edited my comment. 
Having Join on the About sub menu would avoid cluttering, for **Tools** also. Something like this:

- Home
- Events
- Specifications
  - Current
  - Draft
  - Live deploys
- Docs
  - Tutorials
  - Training material
- About
  - Community
  - Groups
  - Join
  - People
  - Presentations
  - Tools

What do you think @ljgarcia @rajido @AlasdairGray ?

**Comment by ljgarcia** [comment]
I would rename Docs to Tools or Hands-on and would have there Tutorials, 
training material and tools... by the way, what is the difference 
between tutorials and training material?

**Comment by AlasdairGray** [comment]
Is there some way we can move the discussion about the menu from this PR to a new issue of PR?

**Comment by ricardoaat** [comment]
Agree, Merging this PR

**Pull request merged**
