### PR TITLE
0.6-DRAFT for ComputationalTool profile 

### PR DESCRIPTION
**Pull request by albangaignard**
Moved from the last DRAFT version to 1.0-RELEASE.

### CODE REVIEW

**Review by matuskalas — APPROVED** [review]
Very cool! 🙌🏽

Is there anything I should particularly review? What I saw looked right 👍🏽

**Review by alaninmcr — APPROVED** [review]
Looks great to me. I think the sooner the release the better.

Well done

**Comment by ljgarcia** [comment]
@albangaignard I did not have time to review this PR but you already have two approvals, I think you can go ahead and merge

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
Before this can be merged in, we need to send it around the community for comment, and then have a Steering Council vote to approve it (see [governance](https://github.com/Bioschemas/governance/blob/master/governance.md#releasing-a-profile)).

**Review by AlasdairGray — APPROVED** [review]
I've made the changes needed to make this the 0.6-DRAFT release.

@albangaignard there are no examples for the 0.6-DRAFT in the [repo](https://github.com/BioSchemas/specifications/tree/master/Tool/examples)

**Pull request merged**
