### PR TITLE
Convert all uses of BioSchemas to Bioschemas

### PR DESCRIPTION
**Pull request by AlasdairGray**
Follow on from the interaction with @martin-nc, I've done a search and replace to eliminate any usage of `BioSchemas` in the website; replacing them all with `Bioschemas`.

I've tested this on my local deployment and checked that the links to the repository work (at least some of them). 

@ljgarcia please can you also verify that this works for you and test some of the links.

### CODE REVIEW

**Comment by alaninmcr** [comment]
When I open a tab to bioschemas.org - the name that appears for the tab is BioSchemas - with an uppercase S.
bioschemas-tab

**Comment by alaninmcr** [comment]
I think the tab name comes from

<title>
  			BioSchemas
  		
  </title>

**Comment by AlasdairGray** [comment]
@alaninmcr is that on the live site or on a local deployment of this branch? If the former then that is what this PR corrects. If the latter then I've missed something.

When I run this branch locally I see the attached.

Screen Shot 2020-10-12 at 16 04 44
Screen Shot 2020-10-12 at 16 04 36

**Comment by alaninmcr** [comment]
@AlasdairGray It was on the deployed site

**Comment by AlasdairGray** [comment]
Thanks for confirming @alaninmcr

**Pull request merged**
