### PR TITLE
Add example deployments of TrainingMaterial

### PR DESCRIPTION
**Pull request by AlasdairGray**
Add details of two known deployments of the TrainingMaterial profile together with a small news item about them.

### CODE REVIEW

**Review by egonw — CHANGES_REQUESTED** [review]
The eNanoMapper entry does not look good. Let me fix that...

**Comment by AlasdairGray** [comment]
Now three deployments

**Comment by AlasdairGray** [comment]
@egonw I assume the changes you wanted are the ones you made in #525. I think we're ready for you to approve heree.

**Comment by egonw** [comment]
> @egonw I assume the changes you wanted are the ones you made in #525. I think we're ready for you to approve heree.

Yes, happy you approve. Cannot find how to do that in the app

**Review by egonw — APPROVED** [review]

**Pull request merged**
