### PR TITLE
Profile versioning

### PR DESCRIPTION
**Pull request by kcmcleod**
PROFILE ONLY attempt at answering:
* https://github.com/BioSchemas/specifications/issues/357 
* https://github.com/BioSchemas/specifications/issues/356

Updated menu and profile page.

Still to delete the old _devSpecs and _specifications folders.

### CODE REVIEW

**Comment by kcmcleod** [comment]
> There is a lot of text at the start of the page which explains release, draft, etc.
There is 1 sentence for release & 1 for deprecated. 0 for draft. The deprecated sentence is long though. I have moved these into the tabs and added a sentence for draft.

**Comment by kcmcleod** [comment]
> Here is a snag list that hopefully can be incorporated fairly easily:
> 
> * [ ]  Taxon release is missing from the release tab. Are there others?
> * [x]  Can we remove the 'Edit me' button from the display of profiles and types?
> * [x]  The 'Latest publication' label is a bit confusing when it points to a working draft, can we change it to 'Latest draft'
> * [x ]  There is a lot of text at the start of the page which explains release, draft, etc. Can this be moved to under the relevant tab so that you only see the text that corresponds to the tab that you are on
> * [ ]  For deprecated profiles, can we also state the date that they were deprecated?
> * [x]  I appreciate that it is helpful to have deprecated profiles for testing purposes, but we'll need to put these all back to draft status until we have informed the community that we are going to deprecate some profiles that have not been used for a while.
> * [x]  The links to profiles in the corresponding group's page is broken
> * [x]  Change the URL of the profiles page from 'bioschemas.org/specifications' to 'bioschemas.org/profiles'



> This is a huge improvement on our existing website. Thanks @kcmcleod for prototyping this. I really appreciate you digging out all the old profile versions as well.
> 
> Here is a snag list that hopefully can be incorporated fairly easily:
> 
> * [ ]  Taxon release is missing from the release tab. Are there others?
> * [x]  Can we remove the 'Edit me' button from the display of profiles and types?
> * [x]  The 'Latest publication' label is a bit confusing when it points to a working draft, can we change it to 'Latest draft'
> * [ ]  There is a lot of text at the start of the page which explains release, draft, etc. Can this be moved to under the relevant tab so that you only see the text that corresponds to the tab that you are on
> * [ ]  For deprecated profiles, can we also state the date that they were deprecated?
> * [x]  I appreciate that it is helpful to have deprecated profiles for testing purposes, but we'll need to put these all back to draft status until we have informed the community that we are going to deprecate some profiles that have not been used for a while.
> * [x]  The links to profiles in the corresponding group's page is broken
> * [x]  Change the URL of the profiles page from 'bioschemas.org/specifications' to 'bioschemas.org/profiles'

**Comment by kcmcleod** [comment]
the conflicting files (_devSpecs/Journal & _devSpecs/SemanticAnnotation) have been replicated in _profiles. as such these files should be deleted when merging.

**Comment by AlasdairGray** [comment]
I have further refined the text at the start of the page and the introduction to the release and draft profiles.

>> digging out all the old profile versions as well.  

> I notice Leyla is still directly editing the specifications:  
> fa0acf8
> b425c8d

This is part of the reason for wanting to remove the edit me button. However, lets make that a separate issue from this one.

@nsjuty @ljgarcia @sarala @CaroleGoble This is where we have got to with the redesign of the display of profiles.   
(We will implement the same style for types once we are happy with the profiles page.)
Screen Shot 2019-11-27 at 16 28 08
Screen Shot 2019-11-27 at 16 28 17
Screen Shot 2019-11-27 at 16 28 20

An individual profile now has links to the latest release version, latest draft version, and the immediate previous draft version. See the following screenshot.
Screen Shot 2019-11-27 at 16 31 54

In the new design, the link bioschemas.org/proiles/Gene will take you to the latest release (or draft if there has not been a release) of the Gene profile, which itself has a link to the latest draft if it has been further refined. (This does not work on the main website yet as we have not merged these changes in.)

@nsjuty @ljgarcia @sarala @CaroleGoble  any comments on the redesign or can we go ahead and merge these in?

@kcmcleod I'm happy with Beacon being deprecated. I wonder if we should have some indication on the profile display page of this deprecated status. At the moment is shows as DRAFT (see screenshot). @nsjuty @ljgarcia @sarala @CaroleGoble  any thoughts on this?
Screen Shot 2019-11-27 at 16 26 57

**Comment by kcmcleod** [comment]
> @kcmcleod I'm happy with Beacon being deprecated. I wonder if we should have some indication on the profile display page of this deprecated status. At the moment is shows as DRAFT (see screenshot).

@AlasdairGray easy to do, but what should it say?
* Beacon DEPRECATED Profile
* Beacon DRAFT Profile (deprecated)
* DEPRECATED: Beacon Draft Profile
* or ?

**Comment by kcmcleod** [comment]
> Can we remove the 'Edit me' button from the display of profiles and types?

@AlasdairGray  added an if statement to header such that button is not displayed when page.spec_type is 'Profile' or 'Type'.

**Comment by ljgarcia** [comment]
@AlasdairGray No editing button anymore? Does it means that we always have to go through the spreadsheets even for already existing profiles and types?

**Comment by AlasdairGray** [comment]
> @AlasdairGray No editing button anymore? Does it means that we always have to go through the spreadsheets even for already existing profiles and types?

Profiles and types should never be edited through the website. The spreadsheet (for profiles) and schemaorg repository (for types) is the original source of the information and is where edits should be made. Any edits made directly on the website would be lost the next time the profile or type are regenerated.

**Comment by AlasdairGray** [comment]
@kcmcleod Are there instructions somewhere for creating and updating profiles with the new page structure?

**Comment by kcmcleod** [comment]
> @kcmcleod Are there instructions somewhere for creating and updating profiles with the new page structure?

@AlasdairGray -  https://github.com/BioSchemas/bioschemas.github.io/wiki

**Comment by ljgarcia** [comment]
The edit button was added because while the spredsheets are useful for new profiles/types, they are painful for existing ones. If I need to fix a type, or add a comma, going to the spreadsheet, make sure GOWeb is up-to-date, remember how to use it because it has been a while, etc. seems too long. We need to find a better way. Something like a web form or so.

**Comment by AlasdairGray** [comment]
If you edit the website without editing the spreadsheet then we lose that edit the next time the webpage is regenerated or the spreadsheet is copied to create a new version of the profile. I agree this is a laborious pain but it is a consequence of choosing the spreadsheets as the source for creating profiles.

I agree a webform would be much easier, but that requires development work that we do not have the resourcing to do.

**Comment by kcmcleod** [comment]
1st draft of types added... needs thorough review

**Comment by AlasdairGray** [comment]
I have now made the release convention for types the same as profiles, i.e. they are either RELEASE or DRAFT. This has removed the RC (RELEASE-CANDIDATE) status.

**Comment by AlasdairGray** [comment]
Revised structure approved by Leadership team during meeting on 19 December 2019 ([minutes](https://docs.google.com/document/d/1ovBDxfqGSOaxg9EkkTiJMZf10hbFIxjGgZRdDLMhmKQ/edit#heading=h.lzk3ns6vu6rn)).

**Comment by AlasdairGray** [comment]
@kcmcleod Can you see why Course, CourseInstance, and TrainingMaterial are not displaying on the profiles page?

**Comment by kcmcleod** [comment]
> @kcmcleod Can you see why Course, CourseInstance, and TrainingMaterial are not displaying on the profiles page?

For course & course instance the version property (in the files) does not match the value in the _data/profiles.yaml. it is case sensitive so DRAFT != draft. 

For training material "0.7-DRAFT-201"  "0.7-DRAFT_201"

I don't have a computer so I cant correct this for you

**Comment by AlasdairGray** [comment]
@kcmcleod Thanks for looking at this. Hopefully that is enough information for me to fix the problem.

**Pull request merged**
