### PR TITLE
Live deploy add node cdr edd

### PR DESCRIPTION
**Pull request by kcmcleod**
Changes:
* Removed identifiers.org as it no longer has markup on homepage.
* Increased biosamples pages from 5 million to over 10
* added node info & CDR/EDD info
* changed stylesheet to ?improve? presentation of highlights & node/CDR info

@AlasdairGray not a fan of the way is this presented. What do you think?

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Thanks for doing this. At the moment it looks strange for non-ELIXIR resources which will not have a node associated with them or be eligible for CDR or DDR status. Therefore, I think it would be better for us to have a separate ELIXIR deployments page, populated from the same yaml file, that only has ELIXIR resources on it.

**Comment by AlasdairGray** [comment]
> Removed identifiers.org as it no longer has markup on homepage.

I suggest that we only comment out Identifiers.org for now. They should have markup again soon.

**Comment by kcmcleod** [comment]
@AlasdairGray  removed all the additions to the LD page. Added an elixir only page, which is linked from the LD page. Any better?

**Comment by kcmcleod** [comment]
Hopefully tackled all critical tasks above PLUS both pages now are closed by default.

Adding ticket for desirable tasks.

**Comment by AlasdairGray** [comment]
I've made some additional refinements to the page overview text and added the legend. 

@kcmcleod please verify and merge if correct.

**Pull request merged**
