### PR TITLE
Add use cases for scholarly publications profiles

### PR DESCRIPTION
**Pull request by ljgarcia**
Solving the issue raised at https://github.com/BioSchemas/specifications/issues/379

### CODE REVIEW

**Comment by ljgarcia** [comment]
Hi @AlasdairGray any news on this PR? Thanks

**Comment by ljgarcia** [comment]
@AlasdairGray I went through the use cases for the release profiles and could not find an example similar to what you mentioned "Alice is searching for publications about protein ACE2?, and then state how Bioschemas will help" so I went a bit blind here but still tried to address your comment.

**Comment by AlasdairGray** [comment]
Thanks for doing that. I'll try to review it later tonight. I'm pushing you in this direction as it is what we are going to require when the new governance framework is in place and it would be good to have an example to point to.

**Comment by AlasdairGray** [comment]
I've tidied up some of the phrasing. I hope you find it acceptable.

**Comment by ljgarcia** [comment]
@AlasdairGray this PR corresponding to [issue 379](https://github.com/BioSchemas/specifications/issues/379) was already merged but the content is not available on the website. See for instance [scholarly article  use cases](https://bioschemas.org/useCases/ScholarlyArticle/). Any idea what could have happen? Will we need to recover the branch, update it and merge it again?

**Comment by AlasdairGray** [comment]
Looks like there is a filename issue. The link on the website goes to https://bioschemas.org/useCases/ScholarlyArticle/ whereas the use case seems to be in the file https://bioschemas.org/useCases/ScholarlyPublications/

**Comment by ljgarcia** [comment]
@AlasdairGray It is a redirection issue. Funny thing, when I run it locally, it works well.

These are the redirections on https://bioschemas.org/useCases/ScholarlyPublications/ 
- "useCases/ScholarlyPublications/"
- "useCases/Journal/"
- "useCases/PublicationIssue"
- "useCases/PublicationVolume"
- "useCases/ScholarlyArticle"
- "useCases/SemanticAnnotation"

The first one is redundant and should be removed, right? Other than that I do not see anything else that could be breaking the redirection on the live version. Should I create a PR removing this redirection and see whether it fixes the problem? As I mentioned, it works well locally.

**Comment by ljgarcia** [comment]
@AlasdairGray Could you please check again? The links are working for me from the profile list page and the profile pages as well. Thanks

**Comment by AlasdairGray** [comment]
Everything seems to be working fine.

**Pull request merged**
