### PR TITLE
add dots

### PR DESCRIPTION
**Pull request by orchid00**
@njall

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Have these changes been made in the cross-walk spreadsheet which is used as the source for this page?

**Comment by AlasdairGray** [comment]
This is connected to [issue 292](https://github.com/BioSchemas/specifications/issues/292).

**Comment by orchid00** [comment]
These are minor formatting changes, I'm not sure which spreadsheet you refer to @AlasdairGray If you have other questions I'm happy to help

**Comment by AlasdairGray** [comment]
@njall have you managed to incorporate these changes into the spreadsheet?

**Comment by AlasdairGray** [comment]
@njall has included these changes in the relevant cross-walk spreadsheet

**Pull request closed without merging**
