### PR TITLE
adding intermine poster from all hands 19 to publications

### PR DESCRIPTION
**Pull request by kcmcleod**
added poster pdf to publications folder as not sure where to put it... ?
do we have other pubs from the all hands?

### CODE REVIEW

**Comment by AlasdairGray** [comment]
It's probably worth adding details of the demo and the tutorial as well with appropriate links.

**Comment by AlasdairGray** [comment]
And there was my presentation to the IDP community

**Comment by kcmcleod** [comment]
> And there was my presentation to the IDP community
I have no details on that, or link to the slides, so I can't add it.

> It's probably worth adding details of the demo and the tutorial as well with appropriate links.
Done.

**Comment by AlasdairGray** [comment]
@kcmcleod I've added a link to the slides I gave for IDP. Please review and merge if you are happy.

**Pull request merged**
