### PR TITLE
Added Bioregistry that now has Dataset annotation

### PR DESCRIPTION
**Pull request by egonw**
cc @cthoyt

### CODE REVIEW

**Comment by egonw** [comment]
The conformsTo is missing, but there is a PR in the making for that: https://github.com/biopragmatics/bioregistry/pull/709

**Comment by cthoyt** [comment]
@egonw that PR is merged and now deployed

**Comment by ljgarcia** [comment]
@egonw any ELIXIR node that should be mentioned for this resource?

**Comment by egonw** [comment]
Actually, I am co-author in the paper. Why not. Yes, let's add NL.

**Review by ljgarcia — APPROVED** [review]
Looks good

**Pull request merged**
