### PR TITLE
Create profile for Matt Styles

### PR DESCRIPTION
**Pull request by AlasdairGray**
@stylesm I've created a profile for you on the Bioschemas website. Let me know if you are happy with these details being added.

### CODE REVIEW

**Comment by AlasdairGray** [comment]
@stylesm pinging you to see if you are happy with this inclusion of your name on the Bioschemas website.

**Comment by AlasdairGray** [comment]
@stylesm please could you let me know if you are happy with this listing on the Bioschemas' website. I would also like to add the Biodiversity group to your profile since you have been active in the discussions there, e.g. [Issue 309](https://github.com/BioSchemas/specifications/issues/309#issuecomment-491770616)

**Comment by stylesm** [comment]
@AlasdairGray I no longer work for UoN or in the bio space, so my profile probably wouldn't be much use :)

**Comment by AlasdairGray** [comment]
Good luck with the new role whatever it may be. Sorry that we can no longer draw on your expertise. I'll close this PR.

**Pull request closed without merging**
