### PR TITLE
Course and CourseInstance 1.0-RELEASE

### PR DESCRIPTION
**Pull request by AlasdairGray**
The Training Working Group have prepared the 1.0-RELEASE version of the Course and CourseInstance profiles ready for community comment. 

Preview versions:
- [Course](https://hw-swel.github.io/bioschemas.github.io/profiles/Course/1.0-RELEASE)
- [CourseInstance](https://hw-swel.github.io/bioschemas.github.io/profiles/CourseInstance/1.0-RELEASE)

Checklist for community approval:

- [x]  Use case present
- [x]  Crosswalk correctly linked with
  - [x]  ~6 minimal properties,
  - [x]  Examples for each property at minimal level
  - [x]  Examples for properties at recommended level
  - [x]  Mapping to terms in equivalent ontologies
- [x]  Relevant issues closed on issue tracker and noted in change history
- [x]  Examples in specification repo
- [x]  Live deploys listing resources with latest version
  - [x]  Example one (https://bioinformatics.ca/workshops-all/2021-infectious-disease-epidemiology-analysis/)
  - [x]  Example two (https://www.ebi.ac.uk/training/events/metagenomics-bioinformatics-2022/)
  - [x]  Example three (https://bioschemas.org/meetings/2022-01_SWAT4HCLS_leiden)
- [x]  Training materials added
- [x]  2 week consultation with community: extended due to summer holiday period – 12 September 2022
- [x]  Community issues adequately addressed
- [x] Update release date and news item date to reflect date approved by Steering Council

This request supersedes #562.

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Training materials stating when to use Course, CourseInstance, and TrainingMaterial added in commit https://github.com/HW-SWeL/bioschemas.github.io/commit/a1b67bd1c49daae606780d30a7e0e0a4f99beb8a and available on the [preview site](https://hw-swel.github.io/bioschemas.github.io/tutorials/howto/howto_right_profile#35-course-courseinstance-and-trainingmaterial).

**Comment by AlasdairGray** [comment]
No issues raised during community consultation period

**Comment by AlasdairGray** [comment]
Release dates updated to date of approval at Steering Council

**Comment by AlasdairGray** [comment]
As agrreed at the Steering Council on 13 September 2022, the Course and CourseInstance profiles are approved for release.

**Review by ljgarcia — APPROVED** [review]
All pending tasks are done now

**Pull request merged**
