### PR TITLE
Add deployments from the Plant Community

### PR DESCRIPTION
**Pull request by AlasdairGray**
the Plant Community have developed deployments on 
- PIPPA: Study and Taxon
- CorkOakDB: Gene and Taxon

@bedroesb any other sites or profiles we should be aware of?

### CODE REVIEW

**Comment by bedroesb** [comment]
@AlasdairGray Thank you for starting this. I totally forgot about this... This looks good to me!

**Comment by AlasdairGray** [comment]
Great. I'll go ahead and transform this into a live PR and get it merged in.

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
@DanFaria is this also ok on your side?

**Comment by AlasdairGray** [comment]
> @DanFaria is this also ok on your side?

We can always make updates if there are changes that are needed.

**Pull request merged**
