### PR TITLE
add VIB live_deployments Course/CourseInstance and TrainingMaterial

### PR DESCRIPTION
**Pull request by abotzki**
Hi, I'd like to add the live deployments of the training related bioschemas profiles to your overview.
Thanks.

### CODE REVIEW

**Comment by abotzki** [comment]
Hi, I would like to ping you to ask when anyone could do a review? Thanks.

**Comment by abotzki** [comment]
Thanks for the feedback - we will implement the `conformsTo` property for Course and CourseInstance. I'll let you know when it is implemented.
I do not know which page you have validated - as to the `courseMode` property, we should be compliant for all our courses (and course instances) which have taken place after the Summer 2023.

**Comment by ljgarcia** [comment]
@abotzki please let me know when the conformsTo has been added.
The page I tried was https://training.vib.be/all-trainings/bulk-rnaseq-counts-differential-expression-3, the one you added as example, markup for the CourseInstance below, no mention of the `courseMode`:
```
"hasCourseInstance": {
                "@type": "CourseInstance",
                "inLanguage": "en-GB",
                "startDate": "2023-06-02",
                "endDate": "2023-06-09",
                "location": {
                    "@type": "Place",
                    "name": "Leuven - Campus Gasthuisberg",
                    "address": {
                        "@type": "PostalAddress",
                        "streetAddress": "Herestraat 49",
                        "addressLocality": "Leuven",
                        "postalCode": "3000",
                        "addressCountry": "BE"
                    }
                },
```
Thanks!

**Comment by abotzki** [comment]
Hi @ljgarcia we have implemented the missing mandatory properties for the Course/CourseInstance properties.

[Please check the example here](https://validator.schema.org/#url=https%3A%2F%2Ftraining.vib.be%2Fall-trainings%2Fbulk-rnaseq-counts-differential-expression-3)

Thanks for your review.

**Review by ljgarcia — APPROVED** [review]
All comments resolved

**Pull request merged**
