### PR TITLE
Profiles training 08draft

### PR DESCRIPTION
**Pull request by ljgarcia**
* Update to DRAFT 0.8 for Course, CourseInstance and TrainingMaterial
* Point to updated examples on specifications repo
* Update use cases
* Update group leads

### CODE REVIEW

**Comment by ljgarcia** [comment]
@AlasdairGray still missing use cases for Course and CourseInstance. While we get that in, could you please look at the TrainingMaterial files I updated? Somehow TrainingMaterial has disappeared from the list of DRAFT profiles but I have no idea why. Thanks

**Comment by ljgarcia** [comment]
@AlasdairGray this PR is ready for review

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
Please remove the update to the working group leads. This change needs to go through the governance processes which have been commenced.

Checks
- [x] Redirects have all been update 
- [x] Pages display correctly
- [x] Links work correctly

Minor quibble:
- [ ] Summary of changes on all three refer to draft 7 rather than 0.7

**Comment by ljgarcia** [comment]
Requested changes done

**Review by AlasdairGray — APPROVED** [review]

**Comment by AlasdairGray** [comment]
Thanks, all looks good for going onto the web

**Pull request merged**
