### PR TITLE
changes as agreed from BioSchemas F2F

### PR DESCRIPTION
**Pull request by sillitoe**

### CODE REVIEW

**Comment by AlasdairGray** [comment]
@sillitoe was a new version of the crosswalk spreadsheet created and used for these changes or is the only version of them in this pull request?

**Comment by sillitoe** [comment]
Sorry, I'm not familiar with the protocol for releases / PRs

We used the following sheet:

https://docs.google.com/spreadsheets/d/1UbTy5OACa08ZTX9yk35AaVRUS6YBm1jBqwgG-Y41KGc/

Does that help?

**Comment by AlasdairGray** [comment]
Thanks @sillitoe. I'll try to stitch things back together so that we have everything in the right place.

**Comment by AlasdairGray** [comment]
I see that @ljgarcia created a new copy of the mapping file for you to create this version of the profile with. It all looks good to me.

**Pull request merged**
