### PR TITLE
Auto-Rendering Profile

### PR DESCRIPTION
**Pull request by sahar-frikha**
This pull request has been created by a guithub action, after adding/updating a profile in the specifications repo.

### CODE REVIEW

**Review by albangaignard — APPROVED** [review]
Looks good in my working copy

**Comment by ljgarcia** [comment]
This PR https://github.com/BioSchemas/bioschemas.github.io/pull/802 should be processed first (now ready and merged).
Embedded mini-examples still missing so will keep it in draft while @gtsueng tells us whether those can be created in the DDE. If not and I add them by hand, will I break sync with DDE?

**Comment by gtsueng** [comment]
@ljgarcia Creating markup is currently not available in the DDE (but is a feature that is in development). The examples should not affect sync with what's in the DDE as those are usually separate files from the profile/type json files in the Specifications Repo.

**Comment by ljgarcia** [comment]
This [PR](https://github.com/BioSchemas/bioschemas.github.io/pull/807) should be processed first

**Comment by ljgarcia** [comment]
@gtsueng @albangaignard @ivanmicetic this is ready to go, could you please review? thanks

**Pull request merged**
