### PR TITLE
Back to top

### PR DESCRIPTION
**Pull request by bedroesb**
New back to top animation: 

Appears automatically using javascript when the page is scrolled beyond the size of the window + makes use of the similar styling currently present on the website

Screenshot from 2021-08-06 11-42-45

### CODE REVIEW

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
Same issue with styling of tables as in Pull #443 (same code removal seems to have taken place).

Really like the floating back to top. However, it doesn't seem to appear on some pages, e.g. http://127.0.0.1:4000/news/

**Comment by bedroesb** [comment]
@AlasdairGray yes, same will appear with the tutorial-restyling branch, I will come with a fix for these branches and close my PR for the CSS reset removal.

**Comment by bedroesb** [comment]
About the news page, that is correct, the page has not the minimum length to appear. The reasoning is that if your page is not long, there is no reason to let it appear. If you make a small window and reload the news page and scroll down, it will appear (it is calculated based on the window length)

**Comment by bedroesb** [comment]
@AlasdairGray I decreased the threshold, now the user has to scroll 1/3 of its window length down for it to appear, do you which it to be sooner?

**Comment by AlasdairGray** [comment]
> @AlasdairGray yes, same will appear with the tutorial-restyling branch, I will come with a fix for these branches and close my PR for the CSS reset removal.

Alternatively remove the CSS reset commit from here and this can be accepted. Then you can fix the styling in the other branch. (Unless there is something else in the styling reset that you are relying on for this back to top to appear.)

**Comment by bedroesb** [comment]
that we can do too :smile:

**Comment by bedroesb** [comment]
Done!

**Review by AlasdairGray — APPROVED** [review]

**Pull request merged**
