### PR TITLE
Biodiversity group and Taxon specification

### PR DESCRIPTION
**Pull request by ricardoaat**
In this PR we have:

- New Group Biodiversity whit @frmichel and @ljgarcia as leaders.
- New draft profile specification Taxon.
- _Other team member_ section on _Contributors_ tab displays now group members. Without including the group leaders. 

Address issue https://github.com/BioSchemas/specifications/issues/115

### CODE REVIEW

**Comment by frmichel** [comment]
@AlasdairGray:
> Taxon specification link on Biodiversity group page is broken. It tries to link to a current version rather than a draft version.
Are you talking about the crosswalk column? 
Do you mean that the link should be to a given version in time, not to the latest (current) version?

> Also the examples folder is missing
It is there: _devSpecs/Taxon/examples,, on branch ric/feat/taon-group for now. Not the right place?

**Comment by AlasdairGray** [comment]
>> Taxon specification link on Biodiversity group page is broken. It tries to link to a current version rather than a draft version.

> Are you talking about the crosswalk column? Do you mean that the link should be to a given version in time, not to the latest (current) version?

No, but until the specification moves to current it only appears on the draft page. This is likely to be the case for the Chemistry and Gene groups as well whose specifications are still in the early draft stage.

> Btw, should we give the link of an editable version? (maybe risky since it will be public on Github).

Yes we encourage edits of the documents.

>> Also the examples folder is missing

> It is there: _devSpecs/Taxon/examples on branch ric/feat/taon-group for now. Not the right place?

The link is not working at the moment.

**Comment by frmichel** [comment]
> The link is not working at the moment.

I'm sorry I don't get it (I'm not so familiar with the whole structure and site generation process).
Where is the link you are referring to? Maybe it will not be valid until the branch has been merged to master?

**Comment by ricardoaat** [comment]
@AlasdairGray @frmichel  I am working on those fixes, will have them in a bit.

**Comment by ricardoaat** [comment]
Hi @AlasdairGray @frmichel, 

Changes are now ready. Please give them a look. 

@AlasdairGray I had to modify the profile-start.html template since Biodiversity is the first group to only one that's not include on people's markdown file. This will fix issue https://github.com/BioSchemas/specifications/issues/195

**Comment by AlasdairGray** [comment]
@ricardoaat thanks for implementing the required changes. However, 
1. the examples folder should be in the specifications repository to be consistent with the other specifications (we should review if this is sensible, but that is a separate issue).
1. we should not repeat the group leads in the list of members

The first of these should be fixed before this pull request is merged in. The second can be moved to part of action https://github.com/BioSchemas/specifications/issues/195

@frmichel sorry for the confusion based on our convoluted approaches.

**Comment by ricardoaat** [comment]
I have copied the examples to the specifications repository, the PR with this can be found here https://github.com/BioSchemas/specifications/pull/197. The link to that folder is fixed on this PR, it will work as soon as the PR 197 is merged. 

@frmichel Thank you for your patience!

**Comment by frmichel** [comment]
Hey, sorry about that newbie questions but I'm a bit confused with how we work with the bioschemas.github.io vs. specifications projects.
"Specifications" is generated using what's in "bioschemas.github.io"?
If I want to make changes to an example or group description, I should do that in bioschemas.github.io, not in specifications, right?

**Comment by AlasdairGray** [comment]
@frmichel please don't apologise for this, the whole thing is overly complicated and is for historic reasons.

bioschemas.github.io is for the website while the currently names specifications repository is for our issue tracking and specification development. 

I've lost track of where the up-to-date editors draft of specifications are sitting after we eliminated our tool for their generation. @kcmcleod @ricardoaat can you clarify this please?

**Comment by kcmcleod** [comment]
@frmichel - the Taxon gSheet is the source for the specifications & examples (both for the website & the specifications repo). Once you have changed the examples/specification please let @ricardoaat know so that he can process your changes with GoWeb (the new specification generation tool).

To change the group description you need to edit the web site (ie the bioschemas.github.io) page: https://github.com/BioSchemas/bioschemas.github.io/blob/master/_groups/Biodiversity.md
Currently we ask for a PR with at least 2 reviews before merging.

**Comment by frmichel** [comment]
Tx @kcmcleod. 

> the Taxon gSheet is the source for the specifications & examples
 
There are some example snipets in the gSheet but we also manage a full example that I first committed it here: https://github.com/BioSchemas/bioschemas.github.io/tree/master/_devSpecs/Taxon/examples

Then, @ricardoaat copied it to https://github.com/BioSchemas/specifications/tree/master/Taxon/examples under another name.

So, which one should I work on to reflect further changes?

Franck.

**Comment by ricardoaat** [comment]
Hello @frmichel 

Perhaps it is a better idea to have the examples on the same project (bioschemas.github.io), but for now the [github specification project](https://github.com/BioSchemas/specifications/tree/master/Taxon/examples ) should be the one used to store the examples as all of the other examples are stored there.

**Comment by frmichel** [comment]
Ok, so while we are working and discussing on the specification, we should commit the draft examples in bioschemas.github.io. Then when we are happy with a version, we copy them to the the specification project. Is that ok with you?

**Pull request merged**
