### PR TITLE
Adding details of known sitemaps

### PR DESCRIPTION
**Pull request by AlasdairGray**

### CODE REVIEW

**Comment by danbri** [comment]
Thanks!

**Comment by petrospaps** [comment]
Hi Alasdair, the sitemaps are added fine, but they are not visible to the user in the live deploys page. Is this the intention or am I looking to the wrong page?

**Comment by AlasdairGray** [comment]
At the moment there is no code to make the sitemaps display. This is an enhancement that we will need to make in the future. However, having the sitemaps in the live deploy data file is still useful.

**Review by petrospaps — APPROVED** [review]
Then everything looks good.

**Pull request merged**
