### PR TITLE
New Dutch resource

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
In the markup you should use `dct:conformsTo` to state which profile you conform to. We also need a statement of this in the YAML for the website.

Is this part of ELIXIR-NL? If so then you should declare the node in the YAML.

**Comment by AlasdairGray** [comment]
You shoudl probably include `DataCatalog` markup on the home page. You have the markup nested within the dataset, but you could use an `@id` reference instead and then only have the DataCatalog markup once.

**Comment by egonw** [comment]
ping @justinjjvanderhooft

**Comment by AlasdairGray** [comment]
Completely agree. It is part of the boilerplate markup for any profile together with `@context`, `@id` and `type`. This is an open issue ([294](https://github.com/BioSchemas/specifications/issues/294) and [481](https://github.com/BioSchemas/specifications/issues/481)).

**Comment by justinjjvanderhooft** [comment]
https://github.com/iomega/paired-data-form

**Comment by egonw** [comment]
> https://github.com/iomega/paired-data-form

Thanks! I'll see if I can create a pull request to translate the comments from Alasdair, or at least the ideas of it.

**Comment by egonw** [comment]
@AlasdairGray, the website landing page already mentions the `DataCatalogue`:

image

How would you suggest to change that? Do you mean it should have the catalogue next to the Website BioSchemas annotation, rather than part of?

**Comment by AlasdairGray** [comment]
@egonw you could remove the redundancy in the markup and change the Dataset markup to
```
"includedInDataCatalog": {
    "@type": "DataCatalog",
    "@id": "https://pairedomicsdata.bioinformatics.nl",
  },
```

**Comment by AlasdairGray** [comment]
I've made a proposal to add the version numbers and also list the DataCatalog separately.

**Comment by egonw** [comment]
@AlasdairGray, just for clarity, this is not my resource :)

**Comment by AlasdairGray** [comment]
BTW, the use of `hasPart` means that the DataCatalog markup is not getting picked up properly by tooling.

It is being picked up for site link search; it is not being picked up for DataCatalog
Screen Shot 2021-02-25 at 21 04 28

**Comment by sverhoeven** [comment]
About `haspart`, I tried to define the DataCatalog in different ways:
1.  DataCatalog as parent. no good I would like to keep WebSite+SearchAction combi.
1. Use  `{"@context":"https://schema.org","@graph":[{"@type":"WebSite",...},{"@type":"DataCatalog",...}]}`
1. Use WebSite.mainEntity
1. Use 2 `<script type="application/ld+json">` tags, one for Website and one for DataCatalog

All of them do **not** show DataCatalog as a primary citizen on https://search.google.com/test/rich-results
I think Google only recognizes DataCatalog when it is part of a Dataset.

I looked at https://github.com/BioSchemas/specifications/tree/master/DataCatalog/examples for inspiration, but could not find a DataCatalog + Website combi.

Any suggestions or best practice?

**Comment by AlasdairGray** [comment]
For Bioschemas we have been recommending that the page is typed as `DataCatalog` but I appreciate that this is not something that you want to do. In that case using `hasPart` or `mainEntityOfPage` is probably appropriate.

I made a mistake in my earlier messages, the Rich Snippets Tool does not make special cases for DataCatalog (I just tested with BioSamples - see [here](https://search.google.com/test/rich-results?id=TiIOxr-CeDGMVM9WLS2UyQ)).

**Comment by AlasdairGray** [comment]
> I've made a proposal to add the version numbers and also list the DataCatalog separately.

If you're happy with these changes then we can merge this PR.

**Comment by sverhoeven** [comment]
OK with me. I kept the `hasPart` and updated https://pairedomicsdata.bioinformatics.nl/ with compliant bioschema profiles.

**Review by AlasdairGray — APPROVED** [review]

**Pull request merged**
