### PR TITLE
add a Dataset 1.0 profile to RiskGONE and group sitemaps in an index

### PR DESCRIPTION
**Pull request by ammar257ammar**
… index

### CODE REVIEW

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
Changes look fine.

Can you change the target branch of the pull request to the branch worked on in https://github.com/BioSchemas/bioschemas.github.io/pull/529?

that way the merge will take place as part of the approval of the 1.0 Dataset release rather than having something claiming to be conformant with a profile that isn't yet approved.

**Comment by ammar257ammar** [comment]
You mean to make a pull request to the repository:brach (HW-SWeL:master) ??

**Comment by AlasdairGray** [comment]
> You mean to make a pull request to the repository:branch (HW-SWeL:master) ??

Yes so that it can be included into the merge when we release Dataset 1.0. I

If that is a crazy idea, just let me know and we'll go ahead with the merge here.

**Comment by ammar257ammar** [comment]
You are right, I agree. I will make a pull request to the other repo and close this PR.
Thanks!!

**Pull request closed without merging**
