### PR TITLE
Live deploy url fix + better back to top

### PR DESCRIPTION
**Pull request by bedroesb**
- the back to top button was not responsive and badly programmed (my fault), now it works immediately 
- in the profiles over view page the live deployments did not deeplink anymore, since the url changed
- fix for weird scroll behavior on the live deploy page

### CODE REVIEW

**Comment by albangaignard** [comment]
Works nicely with Safari, Firefox, Chrome on MacOS/

**Comment by AlasdairGray** [comment]
@albangaignard did you review this PR? Are you happy to accept it and merge it in?

**Comment by albangaignard** [comment]
I'm not listed in the reviewers and don't have any "reviewer" menu. Can you add me as a reviewer ?

**Review by albangaignard — APPROVED** [review]
works nicely on my laptop (MacOS chrome / safari / firefox)

**Pull request merged**
