### PR TITLE
Bioschemas property web pages to prevent 404 errors on profiles

### PR DESCRIPTION
**Pull request by albangaignard**

### CODE REVIEW

**Comment by albangaignard** [comment]
**New menu item for properties  :** 
Capture d’écran 2023-11-01 à 17 40 25

**Comment by albangaignard** [comment]
**New template to render the (flat) list of properties :**  
Capture d’écran 2023-11-01 à 17 41 10

**Comment by albangaignard** [comment]
**New template for each property** 
Capture d’écran 2023-11-01 à 17 41 43

**Review by nsjuty — APPROVED** [review]
looks good

**Comment by nsjuty** [comment]
All previews look good

**Pull request closed without merging**
