### PR TITLE
Ric/livedeploy/adding chembl implementation

### PR DESCRIPTION
**Pull request by ricardoaat**
ChEMBL now implements Dataset and MolecularEntity. Added those to the LiveDeploy page.

### CODE REVIEW

**Comment by ricardoaat** [comment]
We do have plans to include DataCatalog on the website, but right now we have implemented DataSet and MolecularEntity on ChEMBL website, so for now I think it should be include on LiveDeploys Dataset and MolecularEntity sections only.

**Comment by AlasdairGray** [comment]
The markup I looked at included DataCatalog markup

**Comment by ricardoaat** [comment]
Maybe I've missed it, where can I find the markup you looked with DataCatalog?

**Comment by AlasdairGray** [comment]
It was stated that the dataset was in a days catalog and then a description of the catalog was given. Did I misread something?

http://www.macs.hw.ac.uk/~ajg33

________________________________

**Comment by ricardoaat** [comment]
Yes, but it's far from complete. Since we are not including much information of the DataCatalog (not even the minimum for Bioschemas) just yet in the property "includedInDataCatalog", I don't think we could say we properly marked up the DataCatalog type on that JSON-LD. As soon as I have it online it, I believe we could have it as a live deploy.

**Comment by AlasdairGray** [comment]
OK, that's a fair point. I only glanced through it.

**Comment by ricardoaat** [comment]
Thank you!

**Pull request merged**
