### PR TITLE
Workflow 0.5

### PR DESCRIPTION
**Pull request by alaninmcr**
Profiles for Workflow and FormalParameter

### CODE REVIEW

**Comment by stain** [comment]
It seems my review is not valid, could one of the committers approve?

**Comment by AlasdairGray** [comment]
@alaninmcr when you have made the required changes, do you want this PR merged or do you want to get the discussion on the schemaorg repo resolved first ([schemaorg:PR7](https://github.com/BioSchemas/schemaorg/pull/7))?

**Comment by alaninmcr** [comment]
It will be called ComputationalWorkflow 0.5

**Comment by ljgarcia** [comment]
@AlasdairGray regarding the changes you requested: 
* I can see the link to the crosswalk has been corrected, now pointing to 0.5
* Live deploys is green now and I can see the live deploy on the list
* FormalParameter crosswalk link is also correct

@stain still missing:
* Link to example in specifications (there is a link but it is broken)
* Use cases

**Comment by alaninmcr** [comment]
So we need to change the specifications repository?

Plus write at least one use case?

Then we will be good to go?

**Comment by alaninmcr** [comment]
I have added in a use case.

I have also made the specifications folder for the examples.

--
Alan

The University of Manchester belongs to the European R&D infrastructure IBISBA 1.0
The project has received funding from the European Union’s Horizon 2020
Research and Innovation Programme under grant agreement No 730976.
To find out more visit https://www.ibisba.eu

________________________________________

**Comment by alaninmcr** [comment]
Is there any progress on the review?

**Pull request merged**
