### PR TITLE
Release 1.0 of ComputationalWorkflow and FormalParameter

### PR DESCRIPTION
**Pull request by AlasdairGray**
As per the Bioschemas [governance](https://github.com/Bioschemas/governance/blob/master/governance.md) procedures, the working group leads of the [Workflow Group](https://bioschemas.org/groups/Workflow/) have requested that the following types and profiles be considered for release. A 2 week community consultation period will now commence on this submission. On completion, it is expected that all issues will be resolved.

The types and profiles under consideration are:
- ComputationalWorkflow Type [0.1-DRAFT](https://bioschemas.org/types/ComputationalWorkflow/0.1-DRAFT-2020_07_21) to become 1.0-RELEASE: There are no changes between the draft and release version. 
- ComputationalWorkflow Profile [0.5-DRAFT](https://bioschemas.org/profiles/ComputationalWorkflow/0.5-DRAFT-2020_07_21/) to become 1.0-RELEASE: There are no changes between the draft and release version.
- FormalParameter Type [0.1-DRAFT](https://bioschemas.org/types/FormalParameter/0.1-DRAFT-2020_07_21) to become 1.0-RELEASE: There are no changes between the draft and release version.
- FormalParameter Profile [0.1-DRAFT](https://bioschemas.org/profiles/FormalParameter/0.1-DRAFT-2020_07_21) to become 1.0-RELEASE: There are no changes between the draft and release version.

This pull request contains the changes required to convert the current draft versions into release. Any changes requested by the community need to be reflected on this branch prior to approval by the Steering Council.

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Requires issues raised in [#456](https://github.com/BioSchemas/specifications/issues/456) to be addressed

**Review by AlasdairGray — COMMENTED** [review]
@alaninmcr I've started doing a check over the profile. I'm afraid that there are many things that still need to be tidied up. Please can you also add a summary documenting how you have fixed Daniel's issues rather than leaving it for the Steering Council to guess how these have been done.

No change log. A change log from the previous iteration, or a note saying that there is no change needs to be added.

Examples need to be added to the example repo https://github.com/Bioschemas/specifications/tree/master/ComputationalWorkflow/examples/ I have reinstated the link in the profile back to the repo.

Ensure all examples in the profile include the property, e.g. `output` does not show the `output` property

Description of schema properties and types should not be changed. For example, the description of `producer` should be `The person or organization who produced the work (e.g. music album, movie, tv/radio series etc.).` You can add a bioschemas description on the profile that specialises this. Please can you check all descriptions are correct.

**Comment by alaninmcr** [comment]
Thanks Alasdair. Will look at these now

**Comment by AlasdairGray** [comment]
@alaninmcr any update on the progress?

**Comment by alaninmcr** [comment]
> @alaninmcr any update on the progress? It would be good to get this closed off.

Yes. I have made changes, written a change log and also a review response. They are both in the Google drive [folder](https://drive.google.com/drive/folders/10QSvgnEGFXTeOT8qz4-4xwZgLT5GJrqG?usp=sharing). 

I still have to do a full example and an example for a FormalParameter's default value.

**Comment by alaninmcr** [comment]
We are now working on getting a live deploy that satisfies the specification. At the moment there is difficulty in getting the MINIMAL additionalType and format information for the FormalParameters. This information is necessary to help make ComputationalWorkflows FAIR. We have a potential solution.

Alternatively, we could change FornalParameter to have those fields as OPTIONAL. This would reflect what workflow systems can easily produce, but greatly reduce the reusability of workflows.

**Comment by AlasdairGray** [comment]
Thanks for the updates @alaninmcr, please let us know when the working group has come to a resolution on this and updated the release candidate accordingly.

**Comment by alaninmcr** [comment]
Would it be OK if we decided to make the fields OPTIONAL?

**Comment by alaninmcr** [comment]
We have made the properties recommended.

**Comment by AlasdairGray** [comment]
Glad you have come to a consensus. Is there a thread in which this was discussed and can be pointed to?

Should this PR be taken out of draft status?

**Comment by alaninmcr** [comment]
The WorkflowHubClub meets every second Wednesday. So it may be best to wait until the 27th. That way I can check that no one objects to it going to release, and also get a good link for the FormalParameter tweaks.

**Comment by alaninmcr** [comment]
We got official minuted agreement by the workflowHubClub and ELIXIR today. So the FormalParameter change is agreed,

https://docs.google.com/document/d/1oviRCvdRDSD3j1x8XprbkyJm-M11rf6VC-8sPnvb5mo/edit#bookmark=id.rqmjmyz0w9yy

**Comment by ljgarcia** [comment]
Please have a look to comments at https://github.com/BioSchemas/specifications/issues/456

The contributor list in the type and the profile are different, should not they be the same?

There are no examples for 1.0 RELEASE but only for DRAFT 0.5

@AlasdairGray there are some problems with links, I am not sure if they are a general problem or only for this PR:
* at http://127.0.0.1:4000/types/, when hovering I see the local address but when clicking it takes me to the actual bioschemas.org website so the new type links do not work. I tested them manually then. 
* Same thing for the link to the latest released profile at http://127.0.0.1:4000/types/ComputationalWorkflow/1.0-RELEASE/ (when testing the local instance)
* at http://127.0.0.1:4000/types/ComputationalWorkflow/1.0-RELEASE/, the link to ranges on ```documentation```, i.e., ```CreativeWork``` and ```URL``` go to a local page, e.g., http://127.0.0.1:4000/CreativeWork rather than http://schema.org/CreativeWork (it does not happen with ```softwareRequirements``` though
* link to range for ```input``` and ```output``` does not work, it links to http://127.0.0.1:4000/FormalParameter which does not exist (in Bioschemas either profile/ProfileName or type/typeName are possible but directly to the specification is not, i.e., the so call canonical URL does not work)

**Comment by alaninmcr** [comment]
I believe the issues have been addressed. Can you please check?  Thanks

--
Alan

The University of Manchester belongs to the European R&D infrastructure IBISBA 1.0
The project has received funding from the European Union’s Horizon 2020
Research and Innovation Programme under grant agreement No 730976.
To find out more visit https://www.ibisba.eu

________________________________________

**Comment by ljgarcia** [comment]
@alaninmcr I have reviewed the current version. 
@AlasdairGray I still see some issues but @alaninmcr reports they were fixed, please double check in case I am missing something.

- [X] Contributors should be the same in profile and type
- [ ] An example for profile release 1 is needed at https://github.com/BioSchemas/specifications/tree/master/ComputationalWorkflow/example
- [ ] Examples should include dct:conformsTo
- [ ] documentation property should have the same range in type and profile
- [ ] documentation links to http://pending.schema.org/documentation in type but to http://schema.org/documentation in profile
- [X] http://bioschemas.org/FormalParameter redirects to http://bioschema.org/types/FormalParameter/1.0-RELEASE/ and http://bioschemas.org/ComputationalWorkflow redirects to http://bioschema.org/types/ComputationalWorkflow/1.0-RELEASE/ (which seems ok to me) and 

* There is still no profile release 1 example, I can only see an example for DRAFT-0.5, see https://github.com/BioSchemas/specifications/tree/master/ComputationalWorkflow/examples there is only one folder there corresponding to 0.5-DRAFT_examples (if the current example corresponds to release 1, I suggest changing the folder name accordingly although creating a new folder would be better so the history is kept)
* When adding a full example, please make sure you include the line ```"dct:conformsTo": "https://bioschemas.org/profiles/<ProfileName>/<version>```
* I still see CreativeWork or URL as range for documentation in the type but Text or URL in the profile

**Comment by alaninmcr** [comment]
Should be fixed now

**Comment by alaninmcr** [comment]
Should conformsTo also be on the FormalParameters?

**Comment by ljgarcia** [comment]
Yes, please.

**Comment by ljgarcia** [comment]
> 
> 
> Should conformsTo also be on the FormalParameters?

Yes please.

**Comment by ljgarcia** [comment]
Some issues solved now.

@AlasdairGray this might require of your intervention:
* documentation links to http://pending.schema.org/documentation in type but to http://schema.org/documentation in profile

**Comment by alaninmcr** [comment]
OK It is there now, and also I fixed the pending problem.

Are we now good to go?

**Comment by ljgarcia** [comment]
@AlasdairGray should I check FormalParameter as part of this PR as well?

In case yes, some pending issues with FormalParameter:
- [ ] Example must include dc:conformsTo, see https://github.com/BioSchemas/specifications/blob/master/FormalParameter/examples/0.1-DRAFT_examples/example1.jsonld
- [ ] Link to example is missing on the corresponding page /profiles/FormalParameter/1.0-RELEASE/, Links tabs
- [ ] defaultValue property should have the same ranges in type (currently Text and Thing) and profile (currently Thing). if the profile is limiting the range, a note should be included in the Bioschemas description

@AlasdairGray all the issues with ComputationalWorkflow have been solved now. Please confirm whether that is enough for me to accept this PR

@alaninmcr my apologies for not having checked FormalParmeter before in case that becomes a blocker right now for accepting this PR

**Comment by AlasdairGray** [comment]
The changes also make FormalParameter a release so yes it should be checked as well.

**Comment by ljgarcia** [comment]
@alaninmcr I have raised some issues with FormalParameter (see two comments above), please address them as part of this PR. Thanks.

**Comment by alaninmcr** [comment]
I think the issues are fixed

**Comment by ljgarcia** [comment]
It all looks good.

**Comment by alaninmcr** [comment]
@ljgarcia I think you have to approve the review now.

**Review by ljgarcia — APPROVED** [review]
All the identified issues were resolved

**Comment by alaninmcr** [comment]
What is happening with the merge?

**Comment by alaninmcr** [comment]
Many thanks.

**Pull request merged**
