### PR TITLE
Moving to Bootstrap 5 + other improvements

### PR DESCRIPTION
**Pull request by bedroesb**
I couldn't hold myself and gave it a go:

- [x] Moving CSS and JS to an assets directory
- [x] Merging CSS and _SCSS + no stylesheet.css anymore (moved to main.scss)
- [x] Updating to bootstrap 5.1 + making use of its scss files
- [x] No popper.js, part of bootstra.bundle
- [x] Using relative links for everything
- [x] Fixing the deployment on other forks, you can preview this PR [HERE](https://bedroesb.github.io/bioschemas.github.io/) :partying_face: 
  - [x] Home links not working
- [x] New Top navigation bar purely based on bootstrap!
  - [x] Fixing the logo/title in mobile mode
- [x] No separate side mobile nav anymore -> easier to maintain
- [x] Replacing as much of the custom styling with standard bootstrap classes
- [x] Moving logos that are not part of the content to assets/img
- [x] Restructuring the default layout to make it more compatible with WCAG 2.1

Ongoing: Major refactoring -> will wait for further refactoring until the `tutorials-restyling` and `news` branch aremerged into master

TO DO:

- [x] Fixing the modals 
- [x] Fixing animation of logo
- [x] Fixing people/groups that it does not pickup index file
- [x] Publications page
- [x] Fixing Live deploys

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Thanks for taking this on @bedroesb, we'll all benefit from it in the long run, and the site was needing a good overhaul :)

In the test deployment you linked, many of the links are broken, but work fine on my local copy. However, in my local run some links now take me to the live site rather than a page in the local test instance, e.g. clicking on a profile in the live deploys page.

We'll need to review the styling on several pages, the following are just some that I spotted in clicking around:
- [live deploy](https://bedroesb.github.io/bioschemas.github.io/liveDeploys/) table rows don't expand, lots of spacing between table headers
- [publications](https://bedroesb.github.io/bioschemas.github.io/publications/) but I think that is due to the page not reusing styles appropriately
- footer styling

With regard to your comment, are you stalled waiting for these branches to be merged back in?
> Ongoing: Major refactoring -> will wait for further refactoring until the tutorials-restyling and news branch are merged into master

**Comment by bedroesb** [comment]
@AlasdairGray Thanks for reviewing this already, ! Yes, this change is in a premature stage. I know it still has quite some problems, especially the switch to relative links. My goal was to make it easier for people to contribute if they can just deploy there fork in github with 2 clicks. it is more like a first step. I am now in the dilemma of fixing the existing codebase or just starting all over with bootstrap ... :thinking:  

> With regard to your comment, are you stalled waiting for these branches to be merged back in?

Well I made quite some changes in the tutorial restyling branch and also in the news branch, and those will for sure clash with the changes now. I don't what the timing will be for those branches? This refactoring to bootstrap will be a side project in my free anyway :)

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
This looks really good and it is nice that the site is a lot cleaner. Hopefully this will simplify maintenance going forward.

I would like to get @ljgarcia to also look over this PR since it is such an extensive change to the site it is hard for me to be confident that I've checked everything. I doubt that we'll be completely comprehensive even with both of us doing it, but at least we can be more confident that there will be less issues when we go live with this.

I've clicked through a wide selection of pages and tested links and buttons as thoroughly as is reasonable. All seems to be working well except for the following problems that I've spotted:
- [x] Details page of a specific profile, e.g. [ChemicalSubstance](https://bedroesb.github.io/bioschemas.github.io/profiles/ChemicalSubstance/0.4-RELEASE) has the Contributors showing under the Description tab and vice versa. Same issue on the details page of a specific type, e.g. [(localhost):BioChemEntity](http://127.0.0.1:4000/types/BioChemEntity/0.7-RELEASE-2019_06_19/)
- [ ] Relative links in the details page of a specific profile takes you to the live site (this is a problem when testing as you keep being taken out of the test instance)
- [x] Not all links are relative, e.g. the mention of Bioschemas on the live deploys page is hard coded to the site URL.
- [x] Live deploys page by profile tab: link to profile takes you to the profiles overview page rather than to the specific profile.
- [x] Edit me button is covered by the Back to top floating button
- [ ] Edit me button doesn't go to the correct location but that could be because this branch isn't merged in yet and lots of files have been moved around
- [x] How to join in footer goes to 404
- [ ] Funders link in footer goes to 404

**Comment by bedroesb** [comment]
@AlasdairGray great!

> Edit me button doesn't go to the correct location but that could be because this branch isn't merged in yet and lots of files have been moved around

 -> this is correct and will fix itself

> Relative links in the details page of a specific profile takes you to the live site (this is a problem when testing as you keep being taken out of the test instance)

-> It with me it works on the profiles, but not with the types. This is because of the redirects, and is also the case with the current website. A fix is to change url: "http://bioschemas.org" to the one of your local host or your fork, for local testing, this because [redirect_from uses](https://github.com/jekyll/jekyll-redirect-from#prefix) it.

>  Not all links are relative, e.g. the mention of Bioschemas on the live deploys page is hard coded to the site URL.

Can you give an example?

**Comment by bedroesb** [comment]
TODO: 

- [ ] Details page of a specific profile, e.g. [ChemicalSubstance](https://bedroesb.github.io/bioschemas.github.io/profiles/ChemicalSubstance/0.4-RELEASE) has the Contributors showing under the Description tab and vice versa. Same issue on the details page of a specific type, e.g. [(localhost):BioChemEntity](http://127.0.0.1:4000/types/BioChemEntity/0.7-RELEASE-2019_06_19/)
- [ ] Relative links in the details page of a specific profile takes you to the live site (this is a problem when testing as you keep being taken out of the test instance)
- [ ] Not all links are relative, e.g. the mention of Bioschemas on the live deploys page is hard coded to the site URL.
- [ ] Live deploys page by profile tab: link to profile takes you to the profiles overview page rather than to the specific profile.
- [ ] Edit me button is covered by the Back to top floating button
- [ ] Edit me button doesn't go to the correct location but that could be because this branch isn't merged in yet and lots of files have been moved around
- [ ] How to join in footer goes to 404
- [ ] Funders link in footer goes to 404

**Comment by bedroesb** [comment]
@AlasdairGray I fixed the things that I understood, except

> Not all links are relative, e.g. the mention of Bioschemas on the live deploys page is hard coded to the site URL.

I am not so sure what you mean with this one.

**Comment by bedroesb** [comment]
@ljgarcia I think this branch is ready for a second testrun :)

**Comment by ljgarcia** [comment]
Some comments, disregard as needed as some of them might be outside of the scope of this PR
* The banner "Bioschemas Types Included into Schema.org!" has disappeared, is this intentional?
* There are less tutorials in this branch, have you updated from master recently?
* The news are missing
* I thought profiles and _profiles were going to be merged, same with types and _types
* For the types already integrated to schema.org
  * Is the canonical still https://bioschemas.org/<integrated type> ? For instance https://bioschemas.org/BioChemEntity vs https://schema.org/BioChemEntity
  * Properties have been integrated into schema.org as well, should a link to the corresponding on schema.org be included? Example ```associatedDisease``` could link to https://schema.org/associatedDisease
* All the live deploys links take to the top of the page, any possibility of directing to the corresponding expanded profile within the live deploys?
* The issue with the redirection taking you to the live site occurs with types but not with profiles, any idea on what is different there?
* The latest changed for live deploys have not been integrated yet in this fork, have they?
* Some of the non relative links
  * http://bioschemas.org/images/square_logo2.png on index.html
  * http://bioschemas.org/tools/ on technical.md
  * http://bioschemas.org/specifications/ on technical.md
  * <a href="/{{page.name}}">https://bioschemas.org/{{page.name}}</a> on type_start.html
  * <li><a href="http://bioschemas.org/specifications/">Bioschemas specifications</a></li> on 2018-01_italianWorkshop.html

I did not see any of the issues raised by @AlasdairGray so it looks they have been indeed sorted out.

**Comment by bedroesb** [comment]
@ljgarcia it sounds like you looked to the bootsrap5 branch on the bioschemas repo and not on my repo where this PR is made from!

**Comment by bedroesb** [comment]
The only thing that was behind was a change from the live deploys page and the biohackathon meeting, I pulled in these commits now. 

The repo will look like this:

Screenshot from 2021-09-07 16-03-45
Screenshot from 2021-09-07 16-03-37

So things like 
```
There are less tutorials in this branch, have you updated from master recently?
The news are missing
I thought profiles and _profiles were going to be merged, same with types and _types
```

I do not recognize

**Comment by bedroesb** [comment]
concerning 

> The issue with the redirection taking you to the live site occurs with types but not with profiles, any idea on what is different there?

Yes, this is because types use a redirect_from plugin, as described above:
"With me it works on the profiles, but not with the types. This is because of the redirects, and is also the case with the current website. A fix is to change url: "http://bioschemas.org" in _config.yml to the one of your local host or your fork, for local testing, this because redirect_from uses it."

> All the live deploys links take to the top of the page, any possibility of directing to the corresponding expanded profile within the live deploys?

This could be a nice addition in a future PR I agree!

**Comment by bedroesb** [comment]
@ljgarcia and @AlasdairGray great news, I fixed the redirect_from problem by specifying the version in the url, like with the profiles, thank you @ljgarcia for asking what the differences are with the profiles, that made me look twice ;)

**Comment by ljgarcia** [comment]
I can have another look. To avoid further confusion, @bedroesb, what is the URL of the repo I should clone? And what is the branch I have to look at?
Glad spotting the different behavior on redirections between profiles and types solved to sort out the local/site redirection issue

**Comment by bedroesb** [comment]
Normally cloning https://github.com/bedroesb/bioschemas.github.io , with the bootstrap5 branch should be fine. The website can also be previewed [live on my fork](https://bedroesb.github.io/bioschemas.github.io/)

**Comment by bedroesb** [comment]
I also updated the favicon logos to be high resolution: 
image
(left old, right new)

**Comment by AlasdairGray** [comment]
@bedroesb I've fixed the hardcoded URLs

**Comment by bedroesb** [comment]
@AlasdairGray thanks! I don't know how much the feature of deploying bioschemas on your own fork will be used, so I guess replacing all the links on the website with {{ 'url' | relative_url}} is not a high priority for now.

**Review by AlasdairGray — COMMENTED** [review]
From my previous review, the only things that still seem to be causing a problem are:

> - [ ] Relative links in the details page of a specific profile takes you to the live site (this is a problem when testing as you keep being taken out of the test instance)
> - [ ] Edit me button doesn't go to the correct location but that could be because this branch isn't merged in yet and lots of files have been moved around

I believe that the second of these will get fixed when the PR is accepted.

@bedroesb am I correct that the first of these is due to the redirct_from plugin and therefore something that we shouldn't worry about?

**Comment by bedroesb** [comment]
@AlasdairGray 

> Relative links in the details page of a specific profile takes you to the live site (this is a problem when testing as you keep being taken out of the test instance)

I fixed this :thinking: With me both on my [repo](https://bedroesb.github.io/bioschemas.github.io/) and locally, I do not get redirected .... 

> Edit me button doesn't go to the correct location but that could be because this branch isn't merged in yet and lots of files have been moved around

I hope so, it is one of the first things I will test when we merge

**Comment by AlasdairGray** [comment]
I'm testing this by clicking on the BioChemEntity element next to the hasBioChemEntityPart property in the ChemicalSubstance profile.

When I test redirect links on your deployment, https://bedroesb.github.io/bioschemas.github.io/profiles/ChemicalSubstance/0.4-RELEASE, I end up at 404 pages
https://bedroesb.github.io/BioChemEntity/

When I try them on my own local deployment http://127.0.0.1:4000/profiles/ChemicalSubstance/0.4-RELEASE, it claims that it is going to take me to http://127.0.0.1:4000/BioChemEntity/ but when I click on the link I end up at https://bioschemas.org/types/BioChemEntity/0.7-RELEASE-2019_06_19/

**Comment by bedroesb** [comment]
Oh now I found them! I was talking about the [types](https://bedroesb.github.io/bioschemas.github.io/types/) page itselve who had the problem. Okay let me try coming up with a fix!

**Comment by bedroesb** [comment]
@AlasdairGray The only way that I can fix this is by knowing the latest version of the branches it links to, but I don't think I know this if I look at the code. If you link towards a type of profile without the version, it redirects you to the latest version on the live website. Am I correct in saying that this redirect also takes place in the current (old) website if you deploy it locally? I could fix the error 404 on my fork though ...

**Comment by AlasdairGray** [comment]
I had thought that the old site kept you on your local instance, but I have just checked it on the master branch and it has the same behaviour. This then is not an issue that you need to resolve. Sorry for the time and effort that has been spent on this.

**Comment by AlasdairGray** [comment]
@ljgarcia, Bert has resolved all the issues that I had found, are you happy for us to go ahead with the merger?

**Comment by bedroesb** [comment]
@ljgarcia small reminder if you have time to give your approval :)

**Comment by alaninmcr** [comment]
There needs to be more linkage. For example, the mentions of schema.org on the front page do not link to schema.org. Need to link Findability at first use , Web of life

External links should open in a new tab.

Spelling mistake on front page - "Bioscheams". Should be spell checked

IMO the front page is too big. It should be broken into smaller sections.

There is no obvious "contact us"

**Comment by alaninmcr** [comment]
On to getting started

"A quick tour on what this training portal offers". What training portal? First mention of it.

"and posterior inclusion" - that is very strange English

Perhaps rename "Getting started" with "training portal"

Needs a full spelling and grammar check e.g.  "the providers group"

Feedback should be available more generally and not 'hidden' on this page

**Comment by alaninmcr** [comment]
what why schema:

Again, needs much more linkage e.g. RDFa, Yandex

I think this assumes far too much background knowledge.

I don't like the side panel that gives metadata about the page. It is clever that it is generated from the markup :-) If it is kept, then maybe mention its generation.

I'm not sure how helpful the Microdata and RDFa examples are. I think they may just confuse things

**Comment by alaninmcr** [comment]
Found a rather strange link. In /profiles/ the "governance" link went to https://github.com/Bioschemas/governance/blob/master/governance.md

**Comment by alaninmcr** [comment]
The liveDeploys#nav-elixir does not show multiple nodes correctly, It has ["DK", "FR", "ES"] . This is a **bug**

**Comment by bedroesb** [comment]
hello @alaninmcr, is it possible that accept the last comment these things are also th case in the current website? 

The goal PR was to improve the backbone/structure/visuals, not the content :) But this feedback is useful anyway!

**Comment by bedroesb** [comment]
I fixed the node name bug in the live deploys page

**Comment by bedroesb** [comment]
@alaninmcr I also agree on opening external links in different tabs, fixed this in my commit with a javascript snippet

**Comment by alaninmcr** [comment]
I think it is OK to go now. Bert works extremely quickly!

**Comment by AlasdairGray** [comment]
> Found a rather strange link. In /profiles/ the "governance" link went to https://github.com/Bioschemas/governance/blob/master/governance.md
> 
> Same applies for About -> Code of Conduct
> 
> These are **bugs**

This is the way the current website behaves.

**Comment by AlasdairGray** [comment]
> The liveDeploys#nav-elixir does not show multiple nodes correctly, It has ["DK", "FR", "ES"] . This is a **bug**

This is a limitation of jekyl/liquid and not being able to create arrays within liquid.

**Comment by AlasdairGray** [comment]
> I fixed the node name bug in the live deploys page

I'm going to have to look and see how you did this as I spent a lot of time when developing the page to get around that issue and failed.

**Comment by AlasdairGray** [comment]
@alaninmcr thanks for all the useful comments. I've moved these across to [issue 537](https://github.com/BioSchemas/specifications/issues/537).

**Comment by bedroesb** [comment]
@AlasdairGray I reused your line you have currently implemented:

```
{% assign nodeName = node.name | remove: '[' | remove: ']' | remove: '"' | replace: ', ', '-' %}

```

I tried to use `{{ node.name | join: ", "}}` but without success

**Comment by AlasdairGray** [comment]
Looking at the [test deployment](https://bedroesb.github.io/bioschemas.github.io/liveDeploys#nav-elixir/) and the [live page](https://bioschemas.org/liveDeploys/) I don't see any difference. Am I missing something?

Live
Screenshot 2021-09-22 at 14 20 17

Test
Screenshot 2021-09-22 at 14 20 36

**Comment by bedroesb** [comment]
I that not  how it is supposed to look? Alan spotted that it was just printing the list in array form instead of the string now

**Comment by AlasdairGray** [comment]
Ah, OK. Great.

**Comment by AlasdairGray** [comment]
What should really happen, but can't be done in liquid, is redistribute these resources over the nodes, i.e. a multi-node resource would add to the count of each of the nodes so bio.tools would appear under DK, FR, and ES, rather than as a separate line in the table.

**Review by AlasdairGray — APPROVED** [review]

**Comment by bedroesb** [comment]
exciting!

**Pull request merged**
