### PR TITLE
added eNanoMapper Dataset deployment

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by egonw** [comment]
ping @vedina

**Comment by egonw** [comment]
Maybe, not sure. Is in the context of the ELIXIR Tox community.

**Comment by AlasdairGray** [comment]
Happy to take a list of countries, although I think that will break the current website rendering

**Comment by egonw** [comment]
I'm happy to have it without. For Tox Community we can report is elsewhere.

**Comment by egonw** [comment]
Both, I've been following others as examples. Please advise me what further info you like to see me add.

**Comment by ljgarcia** [comment]
Both name and description are minimum for Dataset. Not sure if that is a PR review criterion though

**Comment by egonw** [comment]
Ah, right. In the Bioschemas annotation, not in this pull request. There the `description` is tricky, as that is pulled out with JavaScript and that needs an overhaul of how we add it, and do that in total with JavaScript, not server-side. cc @vedina

**Comment by AlasdairGray** [comment]
We don't tend to enforce conformance as a criteria, if we did we wouldn't have many deployments. If description is problematic then this really is a case where we should not enforce conformance.

**Comment by egonw** [comment]
@ammar257ammar, for your reference, this is the issue to track the progress of finalizing the Bioschemas annotation in the AMBIT software.

**Comment by AlasdairGray** [comment]
@egonw doing some tidying up. I'm closing this PR. 

If eNanoMapper should be listed on the live deploy page, can you create a new entry against the new live deploy page data file.

Thanks, Alasdair

**Pull request closed without merging**
