### PR TITLE
Linkfix

### PR DESCRIPTION
**Pull request by alaninmcr**
This makes the links in the tables correct (I think)

### CODE REVIEW

**Comment by AlasdairGray** [comment]
@alaninmcr which links in particular should this fix?

**Comment by alaninmcr** [comment]
In the HTML page for the profile of ComputationalWorkflow, there are links to FormalParameter. Those links tried (and failed)) to go to schema.org because FormalParameter (and ComputationalWorkflow) were not in the enumerated list of bioschemas types. Putting them into the list makes the links go to bioschemas.

**Comment by AlasdairGray** [comment]
Thanks, that is what I thought. Its just that the links for the types were still not taking me to the respective type when I tried it.

**Comment by alaninmcr** [comment]
Oh boo. Where do they take you to?

--
Alan

The University of Manchester belongs to the European R&D infrastructure IBISBA 1.0
The project has received funding from the European Union’s Horizon 2020
Research and Innovation Programme under grant agreement No 730976.
To find out more visit https://www.ibisba.eu

________________________________________

**Comment by AlasdairGray** [comment]
On the draft ComputationalWorkflow (http://localhost:4000/types/ComputationalWorkflow/0.1-DRAFT-2020_07_21/) it takes me to `http://localhost:4000/types/ComputationalWorkflow/0.1-DRAFT-2020_07_21/#FormalParameter` instead of `http://localhost:4000/FormalParameter`.

Just tested another type (BioChemStructure) and the links there behave as I would expect.

**Comment by alaninmcr** [comment]
Does it work in the profiles? Those are the ones I looked at fixing. I will look at the types now.

**Comment by AlasdairGray** [comment]
Sorry I was looking at the types when you'd clearly said profile earlier in the thread, but best that we get them all sorted.

Type links in the profile and type are behaving as expected, as are property links in the type. I've fixed the behaviour of the property links in the profile.

**Review by AlasdairGray — APPROVED** [review]
Thanks for the fix @alaninmcr

**Pull request merged**
