### PR TITLE
Update profile property ranges as per schema.org latest version (training and labprotocol profiles only)

### PR DESCRIPTION
**Pull request by ljgarcia**
Branch updating keywords and other properties whose ranges have changed in schema.org

### CODE REVIEW

**Comment by ljgarcia** [comment]
@AlasdairGray @petrospaps I created this draft PR so we can add to it the updates required on property ranges as per latest schema.org version. Please add DataCatalog, Dataset and any other you think needs to be updated. I am coordinating scholarly publications and training materials

**Comment by AlasdairGray** [comment]
@ljgarcia I was planning to do the Dataset and DataCatalog on a different PR as I'd like to take the opportunity to look at the other open issues for each of them and resolve them to a 1.0 RELEASE.

**Comment by ljgarcia** [comment]
Ok, I will use this one for training related profiles and lab protocol. All of those related to scholarly publications needed more than just updating ranges so I created a PR for them

**Review by petrospaps — APPROVED** [review]
Looks good.

**Pull request merged**
