### PR TITLE
Rare Disease Tutorial 

### PR DESCRIPTION
**Pull request by AlasdairGray**
I've copied the text supplied by @Orphanet into a tutorial page and linked it into the communities overview page.

@ljgarcia the text of the tutorial needs a read through and probably some revision.

### CODE REVIEW

**Review by ljgarcia — CHANGES_REQUESTED** [review]
Please work on the following issues:
- [ ] The tutorial is not visible in the "Getting Started" menu under the "Community-based tutorials" section
- [ ] Add a link to the community page
- [ ] The text in the Overview section can be improved, e.g., "and" seems to be missing on the second sentence. 
- [ ] It would be useful to include some hints on how this tutorial can be used by others. Right now it describes what was done for a particular case
- [ ] Proof-reading to catch some typos, e.g., well-known rather than well known, Bioschemas has a capital B
- [ ] If possible add a link to the BioHackathon Europe 2019
- [ ] Add links for URL addresses, e.g., schema.org

**Comment by AlasdairGray** [comment]
> * Add a link to the community page

@ljgarcia do you mean on the Community Tutorial Overview page? The link is there already. If you mean another page, please can you give the link of the page that you mean?

**Comment by AlasdairGray** [comment]
@ljgarcia can you check that you are happy for this page to now be included on the site?

**Comment by bedroesb** [comment]
@AlasdairGray we might have to merge first https://github.com/BioSchemas/bioschemas.github.io/pull/507 to have the breadcrumb working

**Review by ljgarcia — APPROVED** [review]

**Comment by bedroesb** [comment]
@ljgarcia this might give conflicts since this PR builds on changes in https://github.com/BioSchemas/bioschemas.github.io/pull/507

**Comment by bedroesb** [comment]
My bad, did't see this :)

**Pull request merged**
