### PR TITLE
Use case template

### PR DESCRIPTION
**Pull request by AlasdairGray**
Introduce a layout template for use cases.

Transferred existing use cases to make use of the template.

### CODE REVIEW

**Comment by ljgarcia** [comment]
@AlasdairGray could you please resolve conflicts before I review?

**Comment by AlasdairGray** [comment]
@ljgarcia that is the issue resolved.

**Review by ljgarcia — APPROVED** [review]
Looks good, opening issues for missing use cases

**Comment by ljgarcia** [comment]
I just realized that there are no use cases for ComputationalTools in this PR but they do exist on the website https://bioschemas.org/useCases/ComputationalTool/
@AlasdairGray please double check why it was not picked up by the template

**Review by ljgarcia — CHANGES_REQUESTED** [review]
ComputationlTool use cases are missing

**Comment by AlasdairGray** [comment]
Computational Tool use case was added after this branch was created and this PR initiated.

Now merged in the master branch, everything should now be present.

**Review by ljgarcia — APPROVED** [review]
All use cases working fine now

**Pull request merged**
