### PR TITLE
Some guidance for when to select MolecularEntity and ChemicalSubstance

### PR DESCRIPTION
**Pull request by egonw**
Implementation of https://github.com/BioSchemas/specifications/issues/554

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Text reads nicely to me.

**Comment by ljgarcia** [comment]
Requires adding a redirection on the profiles pages, a new PR will be created for that

**Comment by ljgarcia** [comment]
Waiting for https://github.com/BioSchemas/bioschemas.github.io/pull/491
Converting into draft by now

**Comment by AlasdairGray** [comment]
If the text is suitable, can we just accept the PR?

The issue with the redirects is orthogonal. If need be, edit the links here so that they work (add or remove the `/`).

**Review by ljgarcia — APPROVED** [review]
Links updated and working

**Comment by ljgarcia** [comment]
> If the text is suitable, can we just accept the PR?
> 
> The issue with the redirects is orthogonal. If need be, edit the links here so that they work (add or remove the `/`).

Done. We might want to add some additional links (e.g., live deploys using the profile) or examples to the guidance but that is for another PR

**Pull request merged**
