### PR TITLE
Add InterPro to list of live deploys

### PR DESCRIPTION
**Pull request by AlasdairGray**
Please can you verify that the information that we have about InterPro's deployment is correct.

Also, do you know the location of the sitemap?

### CODE REVIEW

**Comment by aurel-l** [comment]
Hi Alasdair,

I haven't worked at InterPro for a while now, so I don't know for sure what's the current status of the BioSchema implementation.
Regarding the sitemap, I know there is one, but not sure at what URL.

Tagging @Swaathik and @4ndr01d3 that will know more about this.

**Comment by AlasdairGray** [comment]
@aurel-l thanks for tagging the others in this.

**Comment by Swaathik** [comment]
Hi Alasdair, 

Here is the sitemap location - https://www.ebi.ac.uk/interpro/sitemap/interpro.sitemap.txt

**Comment by AlasdairGray** [comment]
@Swaathik thanks for the sitemap location, I've added that into the details that we have. Are you happy that the details that we have for InterPro's deployment are correct, I include them below for convenience of checking?

BTW, I note that your sitemap is a txt file rather than an xml file that follows the [sitemap recommendations](https://www.sitemaps.org/). Also, it does not list individual pages with the proteins so these still would not be found by tools scraping the site.

```json
{
  "name": "InterPro",
  "description": "Classification of protein families",
  "keywords": [
    "CDR"
  ],
  "url": "https://www.ebi.ac.uk/interpro/",
  "nodes": "EBI",
  "sitemap": "https://www.ebi.ac.uk/interpro/sitemap/interpro.sitemap.txt",
  "profiles": [
    {
      "profileName": "Dataset",
      "conformsTo": "0.3-RELEASE",
      "exampleURL": "https://www.ebi.ac.uk/interpro/"
    },
    {
      "profileName": "ProteinAnnotation",
      "conformsTo": "0.6-DRAFT",
      "exampleURL": "https://www.ebi.ac.uk/interpro/entry/InterPro/IPR015252/",
      "highlight": "Over 38,000 protein entries"
    }
  ]
}
```

**Review by ljgarcia — APPROVED** [review]
Looks fine

**Pull request merged**
