### PR TITLE
Add 2023 pubandtrain

### PR DESCRIPTION
**Pull request by ljgarcia**
Add events and publications from last year that I am aware of.

### CODE REVIEW

**Comment by ljgarcia** [comment]
@albangaignard is this ready to go?

**Review by albangaignard — COMMENTED** [review]
I fixed the CSV + html template, @ljgarcia can you have a look at it ? Then it can be merged. Thanks !

**Comment by ljgarcia** [comment]
Thanks @albangaignard looks good to me, thanks. I cannot merge as I created the initial PR. @albangaignard @ivanmicetic could you please process this PR? Thanks!

**Review by ivanmicetic — APPROVED** [review]
Looks good

**Pull request merged**
