### PR TITLE
ComputationalTool 1.0-RELEASE

### PR DESCRIPTION
**Pull request by AlasdairGray**
@albangaignard I've prepared the 1.0-RELEASE version of ComputationalTool ready for community comment. Can you check that this looks OK to you on your local copy and then we'll get this sent out to the community for comment prior to accepting this branch PR.

I've also started creating a [news item](https://github.com/BioSchemas/bioschemas.github.io/blob/cf0146323c9cdfae975ded44257397f8900ed111/pages/_posts/2021-11-05-ComputationalTool-Profile-1.0-RELEASE.md) about the release. Hopefully you can expand on the features of the ComputationalTools profile.

Checklist for community approval:
- [x] Use case present
- [x] Crosswalk correctly linked with
  - [x]  ~6 minimal properties, 
  - [x] Examples for each property at minimal level
  - [x] Examples for properties at recommended level
  - [x] Mapping to terms in equivalent ontologies
 - [x] Relevant issues closed on issue tracker and noted in change history
 - [x] Examples in specification repo
 - [x] Live deploys listing resources with latest version
   - [x] Example one (https://bridgedb.github.io/)
   - [x] Example two (https://bio.tools/)
- [ ] Training materials added
- [x] 2 week consultation with community
- [x] Community issues adequately addressed

### CODE REVIEW

**Comment by AlasdairGray** [comment]
@ljgarcia we need to send the profile out for a 2 week community review before we can accept this merge request (that is why it is in draft status).

**Comment by ljgarcia** [comment]
@AlasdairGray is this PR ready to go for review? Community consultation is done and we have examples for the new release, would you agree in removing the "draft" status?

**Comment by AlasdairGray** [comment]
We will discuss this at the Steering Council meeting this afternoon.

**Comment by AlasdairGray** [comment]
@albangaignard add paragraph to [Choose the right profile tutorial](https://bioschemas.org/tutorials/howto/howto_right_profile) on when to use ComputationalTool

**Review by ljgarcia — APPROVED** [review]
All working on local deploy

**Pull request merged**
