### PR TITLE
Add details of where Bioschemas has been recommended for use

### PR DESCRIPTION
**Pull request by AlasdairGray**
Adding onto the home page details of where Bioschemas has been recommended for use to help improve the findability of resources.

### CODE REVIEW

**Comment by ljgarcia** [comment]
* I suggest to make it explicit it is not only about data.
Text
> Bioschemas aims to improve the Findability of data  in the life sciences. 
Not only data, we might want to go for digital research objects, digital objects, research objects or something like that as we cover data, software, workflow, training materials.

* I suggest being more specific about findability benefits
Text
> metadata means that you meet some of the Findability criteria of the FAIR Data Principles
Rather than "some" or as a complement, we can include F2 for sure while encouraging F1, F3 and F4. We could also mention some additional effects regarding I1 (particularly on the metadata) and R1.3 while also encouraging R1.1 and R1.2

**Comment by AlasdairGray** [comment]
> * I suggest to make it explicit it is not only about data.
>   Text
> 
> > Bioschemas aims to improve the Findability of data  in the life sciences.
> > Not only data, we might want to go for digital research objects, digital objects, research objects or something like that as we cover data, software, workflow, training materials.

I've tried to address this in 07b675b023349ba78cbb8445791df1b073cf5b15

**Comment by AlasdairGray** [comment]
> * I suggest being more specific about findability benefits
>   Text
> 
> > metadata means that you meet some of the Findability criteria of the FAIR Data Principles
> > Rather than "some" or as a complement, we can include F2 for sure while encouraging F1, F3 and F4. We could also mention some additional effects regarding I1 (particularly on the metadata) and R1.3 while also encouraging R1.1 and R1.2

I think this is getting too detailed for the front page of the website. Perhaps better placed in the training materials. We could include a link to where a reader can find these details.

**Comment by ljgarcia** [comment]
@AlasdairGray I like the changes, thanks!

**Comment by ljgarcia** [comment]
> 
> 
> > * I suggest being more specific about findability benefits
> >   Text
> > 
> > > metadata means that you meet some of the Findability criteria of the FAIR Data Principles
> > > Rather than "some" or as a complement, we can include F2 for sure while encouraging F1, F3 and F4. We could also mention some additional effects regarding I1 (particularly on the metadata) and R1.3 while also encouraging R1.1 and R1.2
> 
> I think this is getting too detailed for the front page of the website. Perhaps better placed in the training materials. We could include a link to where a reader can find these details.

Indeed

**Review by ljgarcia — APPROVED** [review]
Looks good to me

**Pull request merged**
