### PR TITLE
Publications

### PR DESCRIPTION
**Pull request by kcmcleod**
Before I ask Alasdair for feedback, what do you think of the publications page?

### CODE REVIEW

**Comment by ricardoaat** [comment]
The label for the link on the About>Presentation perhaps should include "Publication" word.

**Comment by kcmcleod** [comment]
@ricardoaat  Thanks for the feedback!

Just wondering... are presentations & publications distinct? Should they have a page each? Should the title of the page (and the menu entry) just be Publications?

My current thoughts: publications seems to be a more general term and thus covers presentations. The URL of the page is /publications. Therefore the menu entry should be 'Publications'. Agree?

**Comment by AlasdairGray** [comment]
I've made various updates to the layout of the page.

**Comment by AlasdairGray** [comment]
Not needed for the page to go live, but the content of issue [192](https://github.com/BioSchemas/specifications/issues/192) should be added to the page.

**Comment by AlasdairGray** [comment]
Is there a reason that the embedded slides are not the below code which shows all the slideshows in a single embedded object?

`<iframe src="https://www.slideshare.net/bioschemas/slideshelf" width="615" height="470" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe>`

This is what is deployed on the current publications page?

**Pull request merged**
