### PR TITLE
Added logos and page logos and recommendations

### PR DESCRIPTION
**Pull request by ricardoaat**
On this pull request I have added:
- Bioschemas logos color and white for dark backgrounds.
- Logos and recommendations page
- Link for the page at the end of the Community page (About > Community)
- For discussion: Minor modification to the hexagon logo, hint of curves added to the [logo](https://github.com/BioSchemas/bioschemas.github.io/blob/ric/feat/logos_recommendation_page/images/logos/bioschemas/logo_curve_color.png) in order to resemble more to an [umbrella](https://thumbs.dreamstime.com/z/umbrella-vector-logo-isolated-white-background-88983585.jpg)

### CODE REVIEW

**Comment by ricardoaat** [comment]
I have added a link to the logos page on the About sub-menu, also fixed the links to the images.

**Comment by kcmcleod** [comment]
Why does Hexagon color not have a recommendation? When do we want people to use the full logo and when should they use the hexagon?

**Comment by AlasdairGray** [comment]
The page could just be called Logos

**Comment by kcmcleod** [comment]
Might 'Presentation Guidelines' be a better name than 'recommendations'?

What about changing:
"On slides, whenever is possible, the full logo should be use unless the "Bioschemas" text is too small to be readable; in that case the hexagon could be used."
to:
"Whenever is possible, the full logo should be used. The hexagon logo can be used on slides when the "Bioschemas" text is too small to read."

NOTE: if you don't change the text, there is a typo as it should read "should be useD'.

**Comment by ricardoaat** [comment]
@kcmcleod Thank you! I have followed your recommendations and have created a commit to the branch accordingly. 

@rajido @AlasdairGray Any thoughts?

**Comment by rajido** [comment]
Looks good! great work. Might be just me when I run Jekyll on the branch I got the warning below. Still the site seems to work fine.

Liquid Warning: Liquid syntax error (line 13): Expected dotdot but found pipe in "{{(site.meetings | sort: 'start_date') }}" in index.html
    Liquid Warning: Liquid syntax error (line 6): Expected dotdot but found pipe in "{{(site.meetings | sort: 'start_date') }}" in meetings/index.html

**Comment by AlasdairGray** [comment]
I see those warnings too

**Comment by ricardoaat** [comment]
I've seen them as well, I will create a different PR to fix that bug

**Pull request merged**
