### PR TITLE
Course and CourseInstance Request for Comment

### PR DESCRIPTION
**Pull request by AlasdairGray**
News item announcing Course and CourseInstance ready for community comment.

### CODE REVIEW

**Comment by AlasdairGray** [comment]
Patricia has indicated that they have a revised version of the CourseInstance profile 0.9-DRAFT that has not yet been released. Need to pause this request for community comment until this is resolved.

**Comment by ljgarcia** [comment]
Hi @AlasdairGray 

New PR with the latest draft profiles https://github.com/BioSchemas/bioschemas.github.io/pull/565
* CourseInstance 0.9-DRAFT
* Course 0.10-DRAFT (due to changes on CourseInstance, one Bioschemas description line was removed)

Please have a look, thanks.

**Comment by AlasdairGray** [comment]
New version release versions have been prepared and are available on PR #566

**Comment by AlasdairGray** [comment]
@ljgarcia please can you review this news item PR asking for community comment. Once approved, I'll send a message to the community mailing list.

**Review by ljgarcia — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
