### PR TITLE
Slide links for Data Management workshop at ELIXIR All Hands Meeting

### PR DESCRIPTION
**Pull request by AlasdairGray**

### CODE REVIEW

**Review by albangaignard — COMMENTED** [review]
Slides are open in "write" mode. Can you change access to read-only ?

**Review by albangaignard — CHANGES_REQUESTED** [review]
Slides are open in "write" mode. Can you change access to read-only ?

**Comment by AlasdairGray** [comment]
> Slides are open in "write" mode. Can you change access to read-only ?

Links are already view only if you do not have access to the GDrive folder. You can verify this by opening them in a private browser session.

**Comment by albangaignard** [comment]
Ok, then it's perfect !

**Review by albangaignard — APPROVED** [review]

**Pull request merged**
