### PR TITLE
Dataset 1.0-RELEASE

### PR DESCRIPTION
**Pull request by AlasdairGray**
The Dataset Working Group have prepared the 1.0-RELEASE version of the Dataset profile ready for community comment. 

Checklist for community approval:

- [x]  Use case present
- [x]  Crosswalk correctly linked with
  - [x]  ~6 minimal properties,
  - [x]  Examples for each property at minimal level
  - [x]  Examples for properties at recommended level
  - [x]  Mapping to terms in equivalent ontologies
- [x]  Relevant issues closed on issue tracker and noted in change history
- [x]  Examples in specification repo
- [x]  Live deploys listing resources with latest version
  - [x]  Example one (NanoCommons)
  - [x]  Example two (Wikipathways)
- [x]  Training materials added/updated
- [x]  2 week consultation with community
- [x]  Community issues adequately addressed
- [x] Post news item
- [x] Update any dates associated with the release, e.g. profile publication date and news item date

### CODE REVIEW

**Comment by egonw** [comment]
@AlasdairGray, I updated one live deployment: https://nanocommons.github.io/datasets/

**Comment by AlasdairGray** [comment]
Thanks @egonw. I've updated their release tag in the live deployments file.

**Comment by AlasdairGray** [comment]
@egonw @ljgarcia I don't think that there is anything that needs to be updated in our training materials for this release. Do you both agree?

**Comment by ljgarcia** [comment]
@AlasdairGray agreed, nothing is pending for this release. So, let's go for it!

**Comment by AlasdairGray** [comment]
Great, I've drafted a news item for the publication of the profile
https://hw-swel.github.io/bioschemas.github.io/news/2022-05-16-Dataset-1.0_RELEASE

I'll prepare an email for community comment now.

**Comment by AlasdairGray** [comment]
Need to address:
- [ ] https://github.com/BioSchemas/specifications/issues/574

**Comment by ammar257ammar** [comment]
I made a pull request with a new profile (Dataset 1.0 RELEASE) added to RiskGONE and sitemaps grouped with a sitemap index, approval needed
https://github.com/BioSchemas/bioschemas.github.io/pull/545 
Thanks ^_^

**Review by albangaignard — APPROVED** [review]
Works in my local deployment

**Pull request merged**
