### PR TITLE
Added Ammar Ammar's PSnpBind database.

### PR DESCRIPTION
**Pull request by egonw**
cc @ammar257ammar

### CODE REVIEW

**Comment by egonw** [comment]
@ammar257ammar and I discussed the situation and the missing `conformsTo` will be fixed soon.

**Comment by egonw** [comment]
@AlasdairGray, it's good to go.

**Comment by AlasdairGray** [comment]
Could you also add a quick news item on this one too (see [this](https://github.com/BioSchemas/bioschemas.github.io/pull/521#issuecomment-1061044826) comment for details).

**Comment by egonw** [comment]
> Could you also add a quick news item on this one too (see [this](https://github.com/BioSchemas/bioschemas.github.io/pull/521#issuecomment-1061044826) comment for details).

done.

**Pull request merged**
