### PR TITLE
Move support groups

### PR DESCRIPTION
**Pull request by ljgarcia**
Groups are now grouped in Life Science, Cross-domain, Supporting. The first two are split in active and hibernating.

### CODE REVIEW

**Comment by ljgarcia** [comment]
@albangaignard @ivanmicetic @gtsueng @nsjuty @CaroleGoble could you please have a look to this PR? If you want to quickly see how it would look, go to https://ljgarcia.github.io/bioschemas.github.io/groups/
Once this Pr is approved, I will proceed with the creation of a new Machine Learning Group.
Thanks.

**Comment by ivanmicetic** [comment]
My recommendations:
- [ ] Life Science -> life science
- [ ] Hybernating xxx groups -> Hibernated xxx groups
- [ ] Remove completely the section "Hybernating Life Science groups" if empty
- [ ] "are currently hybernating as there has been no activity in at least 6 months" -> It would be nice to add that a maturity of the group may also be reached, explaining the inactivity. Otherwise it has only a "negative" meaning

**Review by nsjuty — APPROVED** [review]
looks ok

**Comment by ljgarcia** [comment]
@ivanmicetic wrt your recommendations
* Life Science -> life science -- done, using life sciences same as done in the home page
* Hybernating xxx groups -> Hibernated xxx groups -- done
* Remove completely the section "Hybernating Life Science groups" if empty -- I would prefer to keep it even if empty, so it is clear that there is none at the moment but there could be
* "are currently hybernating as there has been no activity in at least 6 months" -> It would be nice to add that a maturity of the group may also be reached, explaining the inactivity. Otherwise it has only a "negative" meaning -- done

Are you happy for the PR to be merged?

**Comment by albangaignard** [comment]
Fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/765/commits/76d52390150e2b0781deb66530d32950c88011cd

**Review by albangaignard — APPROVED** [review]

**Pull request merged**
