### PR TITLE
Update Training.md

### PR DESCRIPTION
**Pull request by ljgarcia**
GDrive link to folder was not working, now fixed

### CODE REVIEW

**Comment by ljgarcia** [comment]
In fact, all links to GDrive folders seem to not work anymore (links to individual docs still work). I need to quickly fix the training one as a paper is under review but we need to fix the others. If anyone else has some time to do so, please go ahead.

**Comment by ivanmicetic** [comment]
I replaced all remaining ".../u/1/..." in gdrive folder URLs. It should be safe to merge.

**Review by albangaignard — APPROVED** [review]
I deployed it locally, everything is fine !

**Review by ivanmicetic — APPROVED** [review]
Looks good. @ljgarcia, you can remove the query part from the URL (?resourcekey...)

**Pull request merged**
