### PR TITLE
add a few dots

### PR DESCRIPTION
**Pull request by orchid00**
@njal

### CODE REVIEW

**Comment by AlasdairGray** [comment]
These changes should be made in the cross-walk spreadsheet

**Comment by AlasdairGray** [comment]
This is connected to [issue 292](https://github.com/BioSchemas/specifications/issues/292).

**Comment by AlasdairGray** [comment]
@njall have you managed to incorporate these changes into the spreadsheet?

**Comment by njall** [comment]
Yep, I've added these too

**Pull request closed without merging**
